//! The FROZEN CONTRACT for `/subagents-detach` — the shared vocabulary between the producer (the
//! foreground driver, which must keep its OS child alive) and the consumer (the slash command,
//! which must render upstream's sentences).
//!
//! Written by the orchestrator BEFORE any implementation so the two halves agree by construction.
//! **Implementations do not edit this file**; a change here changes both halves at once.
//!
//! # What upstream actually does, and why cyrup cannot copy it verbatim
//!
//! `detachForeground` (`src/runs/foreground/execution.ts:612`) is cheap upstream because pi's
//! child is an IN-PROCESS session object: it snapshots progress as `status: "detached"`, builds a
//! receipt with `exitCode = -2`, `detached = true` and `detachedReason`, and returns. **Nothing is
//! killed and nothing is reparented** — the session's callbacks simply keep firing after the tool
//! call has returned.
//!
//! cyrup's foreground child is a REAL OS PROCESS owned by the `drive_foreground_run_sync` future
//! (`extension/executor/foreground.rs:368`). Dropping that future kills the very child the feature
//! exists to keep alive. So a cyrup detach must hand the receipt back to the caller **while the
//! driving future keeps running**, which is a producer-side mechanism this contract deliberately
//! does NOT dictate — only its shape.
//!
//! # What already exists, and must be reused rather than rebuilt
//!
//! The READER half is complete and production-wired; this feature is the missing producer:
//! [`crate::exec::SingleResult::detached`] (`exec/run_result.rs:62`) and `exit_code` (`:28`), the
//! `"detached"` history status (`foreground_history/record.rs:171`) with its never-persist rule,
//! and `ExecutorForegroundProbe` (`extension/executor/wait_subscriptions.rs:78`), already
//! installed at `:291`.

use std::sync::{Arc, Mutex};

use tokio::sync::Notify;

use crate::extension::wait_tool::WAIT_TOOL_NAME;

/// pi `receipt.exitCode = -2` (`execution.ts:618`) — the exit code a detached receipt carries, as
/// distinct from any real process exit.
pub(crate) const DETACHED_EXIT_CODE: i32 = -2;

/// Why a detach was refused, mapping upstream's four guards
/// (`execution.ts:613`: `detached || sessionSettled || lifecycleFinished || signal?.aborted`).
///
/// Upstream collapses all four into a bare `false`. They are named here because the slash command
/// must tell the human WHICH one fired — "not currently detachable" is the sentence, but a log
/// line that cannot say why is the diagnostic-tool lie this project refuses elsewhere.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DetachRefusal {
    /// The run was already detached.
    AlreadyDetached,
    /// Its session had already settled.
    SessionSettled,
    /// Its lifecycle had already finished.
    LifecycleFinished,
    /// The caller's cancellation token was already tripped.
    Aborted,
}

impl DetachRefusal {
    /// The reason, for a log line — never for the model-facing sentence, which is upstream's.
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::AlreadyDetached => "already detached",
            Self::SessionSettled => "session already settled",
            Self::LifecycleFinished => "lifecycle already finished",
            Self::Aborted => "run already aborted",
        }
    }
}

/// Resolving the run a `/subagents-detach [id]` names.
///
/// [`crate::extension::executor::SubagentExecutor::resolve_live_foreground_run`]
/// (`nested_control.rs:211`) returns `Option<String>` and so collapses AMBIGUOUS into NOT-FOUND.
/// Upstream needs three outcomes at two severities (`slash-commands.ts:978-1001`), so the detach
/// path resolves through this instead of widening that function, whose existing callers want the
/// collapse.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum DetachTarget {
    /// Exactly one live foreground run matched.
    Resolved(String),
    /// No live foreground single run at all — upstream's
    /// *"No active foreground single-subagent run to detach."* (`info`, not an error).
    NoneLive,
    /// An id was given and nothing matched it — upstream's
    /// *"No active foreground run found for '{id}'."* (`info`, not an error).
    NoMatch(String),
    /// An id was given and MORE THAN ONE live run matched it as a prefix — upstream's
    /// *"Ambiguous foreground run id prefix '{id}' matched: {…}. Provide a longer id."*
    /// (an `error`, not an `info`).
    ///
    /// This is the with-id case only. When no id is given there is nothing to be ambiguous
    /// ABOUT: the resolver takes upstream's own fallback and picks the most recently updated
    /// `single`-mode control (`slash-commands.ts:246-249`), so several live runs are not a
    /// refusal there.
    ///
    /// It exists because [`crate::extension::executor::SubagentExecutor::resolve_live_foreground_run`]
    /// collapses this into `None`, and answering an ambiguous prefix by picking `first` would
    /// detach a run the human did not name.
    Ambiguous(Vec<String>),
}

// A `DetachOutcome { Detached, Refused, NotSingle }` enum stood here in the frozen contract, as the
// return type the handler was expected to branch on. The implementation that landed never needs it,
// and saying so is cheaper than keeping a type nothing constructs:
//
// * "detached" / "refused" is already [`DetachGate::request`]'s `Result<(), DetachRefusal>` — the
//   refusal reason is carried in the `Err`, so a separate `Refused(DetachRefusal)` arm would only
//   re-wrap it;
// * "not single" is decided BEFORE the gate is reached, off the resolved control's
//   [`crate::extension::executor::notices::ForegroundControlEntry`] `mode`, and is an `Err` notify
//   rather than a value the caller inspects ([`DETACH_NOT_SINGLE_MESSAGE`]);
// * every remaining arm of the resolution is [`DetachTarget`], which the handler DOES match on.
//
// `crate::extension::host::slash_detach`'s `the_handler_renders_each_sentence_for_its_own_outcome`
// covers all five sentences without it.

// =================================================================================================
// The reason a run detached — upstream's `reason: string`, closed
// =================================================================================================

/// Why a foreground run detached. Upstream passes a bare `string`
/// (`execution.ts:612`) and then branches on two known values at four separate sites
/// (`execution.ts:621-630`, `:2006`, `:2143`, `subagent-executor.ts:4209-4213`) with a generic
/// fallback. Closing it here makes those branches exhaustive instead of stringly-typed, and the
/// generic arm disappears because cyrup has exactly the two producers upstream has.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DetachReason {
    /// A child raised a blocking `contact_supervisor` ask and the coordinator handed the run over
    /// (pi `execution.ts:762` — `detachForeground("intercom coordination")`). This is the ONLY
    /// producer cyrup had before `/subagents-detach`.
    IntercomCoordination,
    /// A human fired `/subagents-detach` or its keybinding (pi `subagent-executor.ts:3978` —
    /// `detachForeground?.("user request")`, reached through the control's `detach` callback).
    UserRequest,
}

impl DetachReason {
    /// The wire spelling, byte-identical to upstream's literals — this is what lands in
    /// [`crate::exec::SingleResult::detached_reason`] and what every downstream branch compares.
    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::IntercomCoordination => "intercom coordination",
            Self::UserRequest => "user request",
        }
    }

    /// pi `receipt.finalOutput` (`execution.ts:621-625`).
    pub(crate) const fn final_output(self) -> &'static str {
        match self {
            Self::IntercomCoordination => {
                "Detached for intercom coordination before task completion."
            }
            Self::UserRequest => "Detached at user request before task completion.",
        }
    }

    /// pi `receipt.outputSaveError` (`execution.ts:627-631`) — stamped ONLY when the run had an
    /// output path configured, because that is the file the detach left unfinalized.
    pub(crate) const fn output_save_error(self) -> &'static str {
        match self {
            Self::IntercomCoordination => {
                "Output file was not finalized because the subagent detached for intercom \
                 coordination."
            }
            Self::UserRequest => {
                "Output file was not finalized because the subagent detached at user request."
            }
        }
    }

    /// The model-facing tool result for a detached run — pi `subagent-executor.ts:4206-4213`,
    /// reason-keyed.
    ///
    /// cyrup's current text (`extension/tool/routing.rs:996-1005`) is a paraphrase of the intercom
    /// arm alone and names NEITHER recovery verb, so a model told its run detached has no way to
    /// recover the result. This replaces it.
    pub(crate) fn tool_result_message(self, agent: &str, run_id: &str) -> String {
        let status_recovery = format!(
            "subagent({{ action: \"status\", id: \"{run_id}\" }}) to recover the result; do not \
             resume or launch a replacement while it remains detached."
        );
        match self {
            Self::IntercomCoordination => format!(
                "Detached for intercom coordination: {agent}. Reply to the supervisor request \
                 first, then wait with {WAIT_TOOL_NAME}({{ id: \"{run_id}\" }}). Use \
                 {status_recovery}"
            ),
            Self::UserRequest => format!(
                "Detached at user request: {agent}. The child continues independently. Register a \
                 completion wake-up with {WAIT_TOOL_NAME}({{ id: \"{run_id}\", nonBlocking: true \
                 }}), or use {status_recovery}"
            ),
        }
    }
}

// =================================================================================================
// The four slash-command sentences — pi `slash-commands.ts:978-1001`
// =================================================================================================

/// pi `:990` — an `error` notify, not an `info`.
pub(crate) const DETACH_NOT_SINGLE_MESSAGE: &str =
    "/subagents-detach currently supports single-subagent runs only.";

/// pi `:987` — the no-id, nothing-live case (`info`).
pub(crate) const DETACH_NONE_LIVE_MESSAGE: &str =
    "No active foreground single-subagent run to detach.";

/// pi `:987` — an id was given and matched nothing (`info`).
pub(crate) fn detach_no_match_message(requested: &str) -> String {
    format!("No active foreground run found for '{requested}'.")
}

/// pi `selectForegroundDetachControl`'s throw (`slash-commands.ts:241`), rendered by the handler's
/// catch as an `error` notify (`:982`).
pub(crate) fn detach_ambiguous_message(requested: &str, matched: &[String]) -> String {
    format!(
        "Ambiguous foreground run id prefix '{requested}' matched: {}. Provide a longer id.",
        matched.join(", ")
    )
}

/// pi `:993` — the run exists but its coordinator refused (`info`).
pub(crate) fn detach_refused_message(run_id: &str) -> String {
    format!("Foreground run {run_id} is not currently detachable.")
}

/// pi `:999` — the success sentence, which quotes BOTH recovery verbs by name. The wait verb is
/// [`WAIT_TOOL_NAME`] rather than a literal so this sentence can never drift from the registered
/// tool (that drift is exactly the live bug VL-S8 closes in `watchdog/permission_arbiter.rs`).
///
/// "Pi reload/restart" is rebranded to cyrup's binary name; the disclaimer itself is upstream's
/// and is kept because it is TRUE of cyrup too — the continuation task that keeps driving the
/// child dies with the process.
pub(crate) fn detach_success_message(run_id: &str) -> String {
    format!(
        "Detached foreground run {run_id} without terminating its child. Use \
         subagent({{ action: \"status\", id: \"{run_id}\" }}) or {WAIT_TOOL_NAME}({{ id: \
         \"{run_id}\" }}) to recover the eventual result. This does not daemonize the process or \
         guarantee survival across cyrup reload/restart."
    )
}

// =================================================================================================
// The accept-or-refuse handshake
// =================================================================================================

/// Producer-side state of one foreground run's detachability.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DetachState {
    /// No request outstanding and the run is still detachable.
    Open,
    /// A requester is parked waiting for the driver's verdict.
    Requested(DetachReason),
    /// The driver accepted and published the receipt.
    Accepted,
    /// No longer detachable, for this reason.
    Closed(DetachRefusal),
}

#[derive(Debug)]
struct DetachInner {
    state: Mutex<DetachState>,
    /// Woken when a request arrives (the driver parks here).
    driver: Notify,
    /// Woken when the verdict lands (the requester parks here).
    requester: Notify,
}

/// The DRIVER's half of the handshake, owned by the task that drives the foreground run.
///
/// Upstream needs no such thing: `detachForeground` runs synchronously on the same event loop as
/// the slash handler, so `control.detach?.()` can inspect `detached`/`sessionSettled`/
/// `lifecycleFinished` and answer immediately (`execution.ts:613`). cyrup's driver is a separate
/// task owning a real OS child, so the verdict has to travel — and it must travel in BOTH
/// directions, because upstream's `detach()` returns a `bool` the slash command renders
/// (`slash-commands.ts:993`).
#[derive(Debug)]
pub(crate) struct DetachGate {
    inner: Arc<DetachInner>,
}

impl DetachGate {
    /// A gate for a run that is currently detachable.
    pub(crate) fn new() -> Self {
        Self {
            inner: Arc::new(DetachInner {
                state: Mutex::new(DetachState::Open),
                driver: Notify::new(),
                requester: Notify::new(),
            }),
        }
    }

    /// The consumer-side handle to publish on [`ForegroundControlEntry`]'s `detach` field.
    ///
    /// [`ForegroundControlEntry`]: crate::extension::executor::notices::ForegroundControlEntry
    pub(crate) fn handle(&self) -> ForegroundDetachHandle {
        ForegroundDetachHandle {
            inner: Arc::clone(&self.inner),
        }
    }

    /// Park until a detach is requested, then yield its reason. The driver races this against its
    /// own child-settled future.
    pub(crate) async fn requested(&self) -> DetachReason {
        loop {
            // Register interest BEFORE re-reading the state, so a request that lands between the
            // read and the park cannot be missed.
            let parked = self.inner.driver.notified();
            if let DetachState::Requested(reason) = *lock(&self.inner.state) {
                return reason;
            }
            parked.await;
        }
    }

    /// The driver accepted: the receipt is minted and published, and the run is detached.
    ///
    /// Upstream's ordering is load-bearing and is preserved — `detached = true` is set only AFTER
    /// `onDetachReceipt` returned `true` (`execution.ts:646-648`), so a publish failure leaves the
    /// run attached and abortable rather than orphaned. Call this only once the receipt is out.
    pub(crate) fn accept(&self) {
        *lock(&self.inner.state) = DetachState::Accepted;
        self.inner.requester.notify_one();
    }

    /// The run is no longer detachable — it settled, was cancelled, or the driver could not
    /// publish the receipt. Wakes any parked requester with the refusal it must render.
    ///
    /// A no-op once [`Self::accept`] has run: an accepted detach is terminal, and the later
    /// settlement of the still-live child must not retroactively turn it into a refusal.
    pub(crate) fn close(&self, refusal: DetachRefusal) {
        {
            let mut state = lock(&self.inner.state);
            if matches!(*state, DetachState::Accepted) {
                return;
            }
            *state = DetachState::Closed(refusal);
        }
        self.inner.requester.notify_one();
    }
}

impl Default for DetachGate {
    fn default() -> Self {
        Self::new()
    }
}

/// The CONSUMER's half — what `/subagents-detach`, the keybinding, and the intercom hand-off call.
///
/// This is pi's `ForegroundRunControl.detach` (`shared/types.ts`, lifted from the child by
/// `syncCurrentChild`, `foreground-control.ts:59`). It is deliberately NOT a
/// [`cyrup_core::CancelToken`]: a cancel means *stop*, and the entire point of a detach is that the
/// child keeps running.
#[derive(Debug, Clone)]
pub(crate) struct ForegroundDetachHandle {
    inner: Arc<DetachInner>,
}

impl ForegroundDetachHandle {
    /// Request the detach and wait for the driver's verdict — upstream's `control.detach?.()`
    /// (`slash-commands.ts:993`), whose `false` return is the *"not currently detachable"*
    /// sentence.
    ///
    /// `async` because the verdict comes from another task. It resolves as soon as the driver
    /// accepts or closes the gate; it cannot outlive the run, because the driver closes the gate
    /// on every settle path.
    pub(crate) async fn request(&self, reason: DetachReason) -> Result<(), DetachRefusal> {
        {
            let mut state = lock(&self.inner.state);
            match *state {
                DetachState::Closed(refusal) => return Err(refusal),
                DetachState::Accepted | DetachState::Requested(_) => {
                    return Err(DetachRefusal::AlreadyDetached);
                }
                DetachState::Open => *state = DetachState::Requested(reason),
            }
        }
        self.inner.driver.notify_one();
        loop {
            let parked = self.inner.requester.notified();
            match *lock(&self.inner.state) {
                DetachState::Accepted => return Ok(()),
                DetachState::Closed(refusal) => return Err(refusal),
                DetachState::Open | DetachState::Requested(_) => {}
            }
            parked.await;
        }
    }
}

/// A poisoned detach mutex is not a reason to abort a live child: the gate's state is four plain
/// copy values and no invariant spans an unwind, so the poison is stepped over deliberately.
fn lock(state: &Mutex<DetachState>) -> std::sync::MutexGuard<'_, DetachState> {
    state
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used)]

    use super::*;

    #[tokio::test]
    async fn an_accepted_request_resolves_ok_and_the_driver_sees_the_reason() {
        let gate = DetachGate::new();
        let handle = gate.handle();
        let requester =
            tokio::spawn(async move { handle.request(DetachReason::UserRequest).await });

        assert_eq!(gate.requested().await, DetachReason::UserRequest);
        gate.accept();

        assert_eq!(requester.await.expect("requester task"), Ok(()));
    }

    #[tokio::test]
    async fn a_closed_gate_refuses_with_the_drivers_reason() {
        let gate = DetachGate::new();
        let handle = gate.handle();
        gate.close(DetachRefusal::SessionSettled);

        assert_eq!(
            handle.request(DetachReason::UserRequest).await,
            Err(DetachRefusal::SessionSettled)
        );
    }

    #[tokio::test]
    async fn closing_while_a_requester_is_parked_wakes_it_with_the_refusal() {
        let gate = DetachGate::new();
        let handle = gate.handle();
        let requester =
            tokio::spawn(async move { handle.request(DetachReason::UserRequest).await });

        assert_eq!(gate.requested().await, DetachReason::UserRequest);
        gate.close(DetachRefusal::LifecycleFinished);

        assert_eq!(
            requester.await.expect("requester task"),
            Err(DetachRefusal::LifecycleFinished)
        );
    }

    #[tokio::test]
    async fn a_settle_after_an_accepted_detach_does_not_retract_it() {
        let gate = DetachGate::new();
        let handle = gate.handle();
        let requester =
            tokio::spawn(async move { handle.request(DetachReason::UserRequest).await });
        assert_eq!(gate.requested().await, DetachReason::UserRequest);
        gate.accept();
        assert_eq!(requester.await.expect("requester task"), Ok(()));

        // The child is still alive and will settle later; that settlement closes the gate.
        gate.close(DetachRefusal::SessionSettled);

        // A second request still refuses as ALREADY DETACHED, not as "session settled" — the
        // accepted detach is terminal.
        assert_eq!(
            gate.handle().request(DetachReason::UserRequest).await,
            Err(DetachRefusal::AlreadyDetached)
        );
    }

    #[test]
    fn the_success_sentence_names_the_registered_wait_tool() {
        let message = detach_success_message("run-abc");
        assert!(
            message.contains("bg_wait({ id: \"run-abc\" })"),
            "the recovery verb must be the REGISTERED tool name, got: {message}"
        );
        assert!(message.contains("subagent({ action: \"status\", id: \"run-abc\" })"));
        assert!(message.ends_with("across cyrup reload/restart."));
    }

    #[test]
    fn the_ambiguity_sentence_lists_every_match() {
        assert_eq!(
            detach_ambiguous_message("run", &["run-a".to_string(), "run-b".to_string()]),
            "Ambiguous foreground run id prefix 'run' matched: run-a, run-b. Provide a longer id."
        );
    }

    #[test]
    fn the_two_reasons_carry_upstreams_own_spellings() {
        assert_eq!(DetachReason::UserRequest.as_str(), "user request");
        assert_eq!(
            DetachReason::IntercomCoordination.as_str(),
            "intercom coordination"
        );
        assert_eq!(
            DetachReason::UserRequest.final_output(),
            "Detached at user request before task completion."
        );
    }
}
