;; AGENT-027 fixture: the smallest component that instantiates against the `cyrup:ext@0.10.0`
;; `extension` world and whose `init` succeeds, so the host reaches its `${path} factory` timing mark.
;; It imports nothing and exports every `events` function plus `init`. Each export returns a
;; pointer to zeroed memory, which the canonical ABI reads as the first case / empty value
;; (`init` -> ok, hook-outcome -> noop, option -> none). The four `types` records/variants the
;; events use are exported at the top level so the exported functions only name exported types.
;; Mechanically derived from crates/cyrup-ext/wit/world.wit: when the world changes, regenerate it
;; from the WIT rather than editing it by hand.
(component
  (core module $m
    (memory (export "mem") 1)
    (global $bump (mut i32) (i32.const 1024))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32) (local $p i32)
      global.get $bump local.get 2 i32.add i32.const 1 i32.sub
      i32.const 0 local.get 2 i32.sub i32.and local.tee $p
      local.get 3 i32.add global.set $bump local.get $p)
    (func (export "init") (result i32) i32.const 16)
    (func (export "provider-login") (param i32 i32) (result i32) i32.const 16)
    (func (export "provider-refresh-token") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "provider-get-api-key") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "provider-modify-models") (param i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "provider-stream-simple") (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "autocomplete-suggest") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "with-session") (param i32 i32) (result i32) i32.const 16)
    (func (export "execute-tool") (param i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "prepare-arguments") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "execute-command") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "get-argument-completions") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "execute-shortcut") (param i32 i32) (result i32) i32.const 16)
    (func (export "render-call") (param i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "render-result") (param i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "transform-markdown") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "bash-operations-exec") (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-terminal-input") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-tool-call") (param i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-tool-result") (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-context") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-message-end") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-before-agent-start") (param i32 i32 i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-input") (param i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-user-bash") (param i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-before-provider-request") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-before-provider-headers") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-after-provider-response") (param i32 i32 i32))
    (func (export "on-model-select") (param i32 i32 i32 i32 i32 i32 i32))
    (func (export "on-thinking-level-select") (param i32 i32 i32 i32 i32))
    (func (export "on-agent-start"))
    (func (export "on-agent-end") (param i32 i32))
    (func (export "on-agent-settled"))
    (func (export "on-turn-start") (param i32 i64))
    (func (export "on-turn-end") (param i32 i32 i32 i32 i32))
    (func (export "on-message-start") (param i32 i32))
    (func (export "on-message-update") (param i32 i32 i32 i32))
    (func (export "on-tool-execution-start") (param i32 i32 i32 i32 i32 i32))
    (func (export "on-tool-execution-update") (param i32 i32 i32 i32 i32 i32 i32 i32))
    (func (export "on-tool-execution-end") (param i32 i32 i32 i32 i32 i32 i32))
    (func (export "on-session-start") (param i32 i32 i32 i32 i32))
    (func (export "on-session-shutdown") (param i32 i32 i32 i32 i32))
    (func (export "on-session-info-changed") (param i32 i32 i32))
    (func (export "on-resources-discover") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-project-trust") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-session-before-switch") (param i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-session-before-fork") (param i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-session-before-compact") (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32) i32.const 16)
    (func (export "on-session-compact") (param i32 i32 i32 i32 i32 i32))
    (func (export "on-session-before-tree") (param i32 i32) (result i32) i32.const 16)
    (func (export "on-session-tree") (param i32 i32))
    (func (export "bus-deliver") (param i32 i32 i32 i32))
  )
  (core instance $i (instantiate $m))
  (alias core export $i "mem" (core memory $mem))
  (alias core export $i "realloc" (core func $realloc))
  (type $block-result' (record (field "reason" (option string)) (field "terminate" bool)))
  (export $block-result "block-result" (type $block-result'))
  (type $hook-outcome' (variant (case "noop") (case "block" $block-result) (case "mutate" string) (case "handled" string)))
  (export $hook-outcome "hook-outcome" (type $hook-outcome'))
  (type $tool-output' (record (field "content-json" string) (field "details-json" (option string)) (field "is-error" bool) (field "terminate" bool)))
  (export $tool-output "tool-output" (type $tool-output'))
  (type $terminal-input-result' (record (field "consume" (option bool)) (field "data" (option string))))
  (export $terminal-input-result "terminal-input-result" (type $terminal-input-result'))
  (func $init  (result (result (error string)))
    (canon lift (core func $i "init") (memory $mem) (realloc $realloc)))
  (func $provider-login (param "id" string) (result (result string (error string)))
    (canon lift (core func $i "provider-login") (memory $mem) (realloc $realloc)))
  (func $provider-refresh-token (param "id" string) (param "credentials-json" string) (result (result string (error string)))
    (canon lift (core func $i "provider-refresh-token") (memory $mem) (realloc $realloc)))
  (func $provider-get-api-key (param "id" string) (param "credentials-json" string) (result (result string (error string)))
    (canon lift (core func $i "provider-get-api-key") (memory $mem) (realloc $realloc)))
  (func $provider-modify-models (param "id" string) (param "models-json" string) (param "credentials-json" string) (result (result string (error string)))
    (canon lift (core func $i "provider-modify-models") (memory $mem) (realloc $realloc)))
  (func $provider-stream-simple (param "id" string) (param "stream-id" string) (param "model-json" string) (param "context-json" string) (param "options-json" string) (result (result (error string)))
    (canon lift (core func $i "provider-stream-simple") (memory $mem) (realloc $realloc)))
  (func $autocomplete-suggest (param "base-json" string) (param "query-json" string) (result string)
    (canon lift (core func $i "autocomplete-suggest") (memory $mem) (realloc $realloc)))
  (func $with-session (param "callback-id" string) (result (result (error string)))
    (canon lift (core func $i "with-session") (memory $mem) (realloc $realloc)))
  (func $execute-tool (param "name" string) (param "call-id" string) (param "params-json" string) (result (result $tool-output (error string)))
    (canon lift (core func $i "execute-tool") (memory $mem) (realloc $realloc)))
  (func $prepare-arguments (param "name" string) (param "args-json" string) (result (option string))
    (canon lift (core func $i "prepare-arguments") (memory $mem) (realloc $realloc)))
  (func $execute-command (param "name" string) (param "args" string) (result (result (option string) (error string)))
    (canon lift (core func $i "execute-command") (memory $mem) (realloc $realloc)))
  (func $get-argument-completions (param "name" string) (param "prefix" string) (result (list string))
    (canon lift (core func $i "get-argument-completions") (memory $mem) (realloc $realloc)))
  (func $execute-shortcut (param "key" string) (result (result (error string)))
    (canon lift (core func $i "execute-shortcut") (memory $mem) (realloc $realloc)))
  (func $render-call (param "custom-type" string) (param "call-json" string) (param "opts-json" string) (result (option string))
    (canon lift (core func $i "render-call") (memory $mem) (realloc $realloc)))
  (func $render-result (param "custom-type" string) (param "result-json" string) (param "opts-json" string) (result (option string))
    (canon lift (core func $i "render-result") (memory $mem) (realloc $realloc)))
  (func $transform-markdown (param "markdown" string) (param "ctx-json" string) (result string)
    (canon lift (core func $i "transform-markdown") (memory $mem) (realloc $realloc)))
  (func $bash-operations-exec (param "call-id" string) (param "command" string) (param "cwd" string) (param "opts-json" string) (result (result (option s32) (error string)))
    (canon lift (core func $i "bash-operations-exec") (memory $mem) (realloc $realloc)))
  (func $on-terminal-input (param "data" string) (result (option $terminal-input-result))
    (canon lift (core func $i "on-terminal-input") (memory $mem) (realloc $realloc)))
  (func $on-tool-call (param "call-id" string) (param "name" string) (param "input-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-tool-call") (memory $mem) (realloc $realloc)))
  (func $on-tool-result (param "call-id" string) (param "name" string) (param "input-json" string) (param "content-json" string) (param "is-error" bool) (param "details-json" (option string)) (param "usage-json" (option string)) (result $hook-outcome)
    (canon lift (core func $i "on-tool-result") (memory $mem) (realloc $realloc)))
  (func $on-context (param "messages-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-context") (memory $mem) (realloc $realloc)))
  (func $on-message-end (param "message-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-message-end") (memory $mem) (realloc $realloc)))
  (func $on-before-agent-start (param "prompt" string) (param "images-json" string) (param "system-prompt" string) (param "options-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-before-agent-start") (memory $mem) (realloc $realloc)))
  (func $on-input (param "text" string) (param "images-json" string) (param "source" string) (param "streaming-behavior" (option string)) (result $hook-outcome)
    (canon lift (core func $i "on-input") (memory $mem) (realloc $realloc)))
  (func $on-user-bash (param "command" string) (param "exclude-from-context" bool) (param "cwd" string) (result $hook-outcome)
    (canon lift (core func $i "on-user-bash") (memory $mem) (realloc $realloc)))
  (func $on-before-provider-request (param "payload-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-before-provider-request") (memory $mem) (realloc $realloc)))
  (func $on-before-provider-headers (param "headers-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-before-provider-headers") (memory $mem) (realloc $realloc)))
  (func $on-after-provider-response (param "status" u32) (param "headers-json" string)
    (canon lift (core func $i "on-after-provider-response") (memory $mem) (realloc $realloc)))
  (func $on-model-select (param "model-json" string) (param "previous-model-json" (option string)) (param "source" string)
    (canon lift (core func $i "on-model-select") (memory $mem) (realloc $realloc)))
  (func $on-thinking-level-select (param "level" string) (param "previous-level" (option string))
    (canon lift (core func $i "on-thinking-level-select") (memory $mem) (realloc $realloc)))
  (func $on-agent-start 
    (canon lift (core func $i "on-agent-start") (memory $mem) (realloc $realloc)))
  (func $on-agent-end (param "messages-json" string)
    (canon lift (core func $i "on-agent-end") (memory $mem) (realloc $realloc)))
  (func $on-agent-settled 
    (canon lift (core func $i "on-agent-settled") (memory $mem) (realloc $realloc)))
  (func $on-turn-start (param "turn-index" u32) (param "timestamp" u64)
    (canon lift (core func $i "on-turn-start") (memory $mem) (realloc $realloc)))
  (func $on-turn-end (param "turn-index" u32) (param "message-json" string) (param "tool-results-json" string)
    (canon lift (core func $i "on-turn-end") (memory $mem) (realloc $realloc)))
  (func $on-message-start (param "message-json" string)
    (canon lift (core func $i "on-message-start") (memory $mem) (realloc $realloc)))
  (func $on-message-update (param "message-json" string) (param "delta-json" string)
    (canon lift (core func $i "on-message-update") (memory $mem) (realloc $realloc)))
  (func $on-tool-execution-start (param "call-id" string) (param "name" string) (param "args-json" string)
    (canon lift (core func $i "on-tool-execution-start") (memory $mem) (realloc $realloc)))
  (func $on-tool-execution-update (param "call-id" string) (param "name" string) (param "args-json" string) (param "chunk-json" string)
    (canon lift (core func $i "on-tool-execution-update") (memory $mem) (realloc $realloc)))
  (func $on-tool-execution-end (param "call-id" string) (param "name" string) (param "result-json" string) (param "is-error" bool)
    (canon lift (core func $i "on-tool-execution-end") (memory $mem) (realloc $realloc)))
  (func $on-session-start (param "reason" string) (param "previous-session-file" (option string))
    (canon lift (core func $i "on-session-start") (memory $mem) (realloc $realloc)))
  (func $on-session-shutdown (param "reason" string) (param "target-session-file" (option string))
    (canon lift (core func $i "on-session-shutdown") (memory $mem) (realloc $realloc)))
  (func $on-session-info-changed (param "name" (option string))
    (canon lift (core func $i "on-session-info-changed") (memory $mem) (realloc $realloc)))
  (func $on-resources-discover (param "cwd" string) (param "reason" string) (result $hook-outcome)
    (canon lift (core func $i "on-resources-discover") (memory $mem) (realloc $realloc)))
  (func $on-project-trust (param "cwd" string) (result $hook-outcome)
    (canon lift (core func $i "on-project-trust") (memory $mem) (realloc $realloc)))
  (func $on-session-before-switch (param "reason" string) (param "target-session-file" (option string)) (result $hook-outcome)
    (canon lift (core func $i "on-session-before-switch") (memory $mem) (realloc $realloc)))
  (func $on-session-before-fork (param "entry-id" string) (param "position" string) (result $hook-outcome)
    (canon lift (core func $i "on-session-before-fork") (memory $mem) (realloc $realloc)))
  (func $on-session-before-compact (param "preparation-json" string) (param "branch-entries-json" string) (param "custom-instructions" (option string)) (param "reason" string) (param "will-retry" bool) (result $hook-outcome)
    (canon lift (core func $i "on-session-before-compact") (memory $mem) (realloc $realloc)))
  (func $on-session-compact (param "compaction-entry-json" string) (param "from-extension" bool) (param "reason" string) (param "will-retry" bool)
    (canon lift (core func $i "on-session-compact") (memory $mem) (realloc $realloc)))
  (func $on-session-before-tree (param "preparation-json" string) (result $hook-outcome)
    (canon lift (core func $i "on-session-before-tree") (memory $mem) (realloc $realloc)))
  (func $on-session-tree (param "event-json" string)
    (canon lift (core func $i "on-session-tree") (memory $mem) (realloc $realloc)))
  (func $bus-deliver (param "topic" string) (param "payload-json" string)
    (canon lift (core func $i "bus-deliver") (memory $mem) (realloc $realloc)))
  (instance $events
    (export "provider-login" (func $provider-login))
    (export "provider-refresh-token" (func $provider-refresh-token))
    (export "provider-get-api-key" (func $provider-get-api-key))
    (export "provider-modify-models" (func $provider-modify-models))
    (export "provider-stream-simple" (func $provider-stream-simple))
    (export "autocomplete-suggest" (func $autocomplete-suggest))
    (export "with-session" (func $with-session))
    (export "execute-tool" (func $execute-tool))
    (export "prepare-arguments" (func $prepare-arguments))
    (export "execute-command" (func $execute-command))
    (export "get-argument-completions" (func $get-argument-completions))
    (export "execute-shortcut" (func $execute-shortcut))
    (export "render-call" (func $render-call))
    (export "render-result" (func $render-result))
    (export "transform-markdown" (func $transform-markdown))
    (export "bash-operations-exec" (func $bash-operations-exec))
    (export "on-terminal-input" (func $on-terminal-input))
    (export "on-tool-call" (func $on-tool-call))
    (export "on-tool-result" (func $on-tool-result))
    (export "on-context" (func $on-context))
    (export "on-message-end" (func $on-message-end))
    (export "on-before-agent-start" (func $on-before-agent-start))
    (export "on-input" (func $on-input))
    (export "on-user-bash" (func $on-user-bash))
    (export "on-before-provider-request" (func $on-before-provider-request))
    (export "on-before-provider-headers" (func $on-before-provider-headers))
    (export "on-after-provider-response" (func $on-after-provider-response))
    (export "on-model-select" (func $on-model-select))
    (export "on-thinking-level-select" (func $on-thinking-level-select))
    (export "on-agent-start" (func $on-agent-start))
    (export "on-agent-end" (func $on-agent-end))
    (export "on-agent-settled" (func $on-agent-settled))
    (export "on-turn-start" (func $on-turn-start))
    (export "on-turn-end" (func $on-turn-end))
    (export "on-message-start" (func $on-message-start))
    (export "on-message-update" (func $on-message-update))
    (export "on-tool-execution-start" (func $on-tool-execution-start))
    (export "on-tool-execution-update" (func $on-tool-execution-update))
    (export "on-tool-execution-end" (func $on-tool-execution-end))
    (export "on-session-start" (func $on-session-start))
    (export "on-session-shutdown" (func $on-session-shutdown))
    (export "on-session-info-changed" (func $on-session-info-changed))
    (export "on-resources-discover" (func $on-resources-discover))
    (export "on-project-trust" (func $on-project-trust))
    (export "on-session-before-switch" (func $on-session-before-switch))
    (export "on-session-before-fork" (func $on-session-before-fork))
    (export "on-session-before-compact" (func $on-session-before-compact))
    (export "on-session-compact" (func $on-session-compact))
    (export "on-session-before-tree" (func $on-session-before-tree))
    (export "on-session-tree" (func $on-session-tree))
    (export "bus-deliver" (func $bus-deliver))
  )
  (export "cyrup:ext/events@0.10.0" (instance $events))
  (export "init" (func $init))
)
