//! The TypeSafe provider (1:1 port of pi `packages/ai/src/providers/typesafe.ts` and its generated
//! `typesafe.models.ts` @f1b2e77f5, PROV-153).
//!
//! Upstream, verbatim:
//!
//! ```ts
//! export function typesafeProvider(): Provider {
//!     return createProvider({
//!         id: "typesafe",
//!         name: "TypeSafe",
//!         auth: { apiKey: envApiKeyAuth("TypeSafe API key", ["TYPESAFE_API_KEY"]) },
//!         models: Object.values(TYPESAFE_CLASSIFIER_MODELS),
//!         classifiers: { "typesafe-system-one": typesafeSystemOneApi() },
//!     });
//! }
//! ```
//!
//! It is the one built-in with NO chat model and no chat `api`: its catalog is classifier rows only
//! (`TYPESAFE_CLASSIFIER_MODELS`, generated by `loadModelsDevClassifierModels` from models.dev's
//! `typesafe/jev-latest` decision model, `scripts/generate-models.ts:2586-2617`), so it can
//! `classify` and do nothing else — [`crate::provider::Provider::models`] is empty and
//! [`crate::provider::Provider::get_all_models`] holds the classifier rows. TypeSafe's own System
//! One endpoint (`https://api.typesafe.ai/v1/systemone`) is reached through
//! [`crate::api::typesafe_system_one`], the api OpenRouter's TypeSafe rows already use (PROV-104).
//! pi sets no provider `baseUrl`; each row carries its own.

use crate::api::ApiRegistry;
use crate::auth::{CredentialStore, InMemoryCredentialStore, ProviderAuth, env_key};
use crate::classifier::{ClassifierApiRegistry, ClassifierModel, KnownClassifierApi};
use crate::wire::WireProvider;
use std::sync::Arc;

/// The provider id (pi `KnownProvider` `"typesafe"`, `types.ts:97`).
pub const TYPESAFE_PROVIDER_ID: &str = "typesafe";

/// The env var carrying the TypeSafe API key (pi `envApiKeyAuth("TypeSafe API key",
/// ["TYPESAFE_API_KEY"])`, `typesafe.ts:11`; `env-api-keys.ts:98`).
pub const TYPESAFE_API_KEY_ENV: &str = "TYPESAFE_API_KEY";

/// The classifier rows, generated by `xtask gen-catalogs` from
/// `pi.dev/api/models/providers/typesafe?types=classifier`.
const TYPESAFE_CLASSIFIER_CATALOG_JSON: &str = include_str!("catalog/typesafe-classifiers.json");

/// The TypeSafe classifier catalog (1:1 with pi `TYPESAFE_CLASSIFIER_MODELS`). A parse failure
/// yields an empty list, surfaced by the catalog tests, rather than a panic.
pub fn typesafe_classifier_models() -> Vec<ClassifierModel> {
    crate::catalog::load_classifier_catalog(TYPESAFE_CLASSIFIER_CATALOG_JSON).unwrap_or_default()
}

/// The TypeSafe [`ProviderAuth`]: an API key from `$TYPESAFE_API_KEY` and nothing else.
pub fn typesafe_auth() -> ProviderAuth {
    ProviderAuth {
        api_key: Some(env_key("TypeSafe API key", [TYPESAFE_API_KEY_ENV])),
        oauth: None,
    }
}

/// The provider's `classifiers` dispatch map (pi `classifiers: { "typesafe-system-one":
/// typesafeSystemOneApi() }`, `typesafe.ts:14-16`).
pub fn typesafe_classifiers_registry() -> ClassifierApiRegistry {
    let kind = KnownClassifierApi::TypesafeSystemOne;
    let mut registry = ClassifierApiRegistry::new();
    registry.register(kind, kind.implementation());
    registry
}

/// Construct the TypeSafe provider over the given credential store.
///
/// It takes no api registry because pi's `typesafeProvider()` passes no `api`: an EMPTY registry
/// makes any chat stream through it fail (`no API implementation for <api>`), as pi's
/// `createProvider` answers `Provider typesafe has no API implementation for "<api>"`
/// (`models.ts:1076-1080`), instead of dispatching a chat model it was handed through the shared
/// built-in registry under TypeSafe's key.
pub fn typesafe_provider_with(store: Arc<dyn CredentialStore>) -> WireProvider {
    WireProvider::new(
        TYPESAFE_PROVIDER_ID,
        "TypeSafe",
        Vec::new(),
        typesafe_auth(),
        store,
        Arc::new(ApiRegistry::new()),
    )
    .with_classifier_models(typesafe_classifier_models())
    .with_classifiers(Arc::new(typesafe_classifiers_registry()))
}

/// Convenience constructor: an in-memory credential store.
pub fn typesafe_provider() -> WireProvider {
    typesafe_provider_with(Arc::new(InMemoryCredentialStore::new()))
}
