//! Embedded model-catalog data correctness (PROV-004).
//!
//! # Provenance
//!
//! cyrup ships **35** catalogs under `src/providers/catalog/*.json`. Thirty of them are a
//! **byte-faithful snapshot of pi @ `5c1a2977`** ("fix(ai): update generated model catalogue", 2026-06-30):
//! diffing every catalog field-by-field against that revision comes out identical for 30 of the 30
//! files that have a `packages/ai/src/providers/*.models.ts` counterpart, modulo three deltas that
//! upstream itself later adopted.
//!
//! pi then refreshed the catalogs seventeen times between `5c1a2977` and `91585d9a`
//! (2026-07-10 16:34) — the revision matching cyrup's own HEAD baseline date. cyrup never picked
//! that window up, so the embedded data was stale against cyrup's *own* declared baseline. This is
//! **owed debt, not post-baseline drift**: every commit cited below landed before 2026-07-10.
//!
//! The commits in that window that moved data these tests pin:
//!
//! | pi commit | date | effect |
//! |---|---|---|
//! | `cc2db980` | 2026-07-08 | switched generation to models.dev per-provider catalogs — retired 10 EOL Claude models, raised Sonnet 4.5 to 1M context, fixed `mistral-medium-latest`, zeroed the Xiaomi token-plan (prepaid) rates |
//! | `46145bef` | 2026-07-09 | OpenRouter context windows now come from the *top serving provider* rather than the theoretical model max |
//! | `fbdd4638` | 2026-07-09 | added the `max` thinking rung (covered by `thinking_max.rs`, PROV-002/DRIFT-008) |
//! | `7df2a94e` | 2026-07-09 | GPT-5.6 (`luna`/`sol`/`terra`) metadata |
//! | `5b4bda30`, `ee24a9ec`, `72d77b53`, `1da1cdb2`, `844d175e` | 2026-07-08..09 | generated-catalog refreshes |
//!
//! # Why these tests exist
//!
//! Every catalog is `include_str!`-ed and parsed with `serde_json::from_str(..).unwrap_or_default()`
//! (e.g. `providers/anthropic.rs:30`). A malformed edit therefore yields an **empty** provider
//! catalog with no diagnostic whatsoever — the failure is completely silent, and the only symptom
//! is a provider that mysteriously offers no models. `every_embedded_catalog_parses_non_empty`
//! closes that hole for the whole set, and the value assertions below stop a *well-formed but
//! wrong* number from going unnoticed.
//!
//! # Provenance, as of 2026-08-15 — the history above is history
//!
//! **None of the hand-snapshot story above describes the current files.** Every catalog under
//! `src/providers/catalog/`, and `catalog_manifest.json` with them, is now GENERATED by
//! `cargo run -p xtask -- gen-catalogs` from ONE pinned pi revision, `b0c2a90e` (2026-07-17). The
//! split that produced everything the tests below pin — 31 files taken at `91585d9a`, four at
//! `b0c2a90e`, and nobody able to say which — is gone, and `gen-catalogs --check` fails if a file
//! stops reproducing (PROV-018/PROV-060).
//!
//! The premise that made this unauditable, recorded as settled fact by nine sweeps and by
//! `PARITY-GAPS.md`'s `OQ-5`, was FALSE: pi gitignores `providers/data/` and collapses every
//! `*.models.ts` to a two-line re-export only from `a9f6a3159` onward. `b0c2a90e` is that commit's
//! direct PARENT and the revision cyrup's manifest already named, and there the modules are full
//! data literals. `git show` plus `xtask/src/tsdata.rs` recovers all of it — no generator run, no
//! `npm install`, no network. The five files this header used to call un-diffable, including the
//! 109-row `amazon-bedrock.json`, are diffed field-by-field by that command like every other.
//!
//! **The residue, stated so these tests are not read as proof of parity at the ported tag:**
//! `b0c2a90e` is 13 days older than `v0.83.0`, and the catalog data for those 13 days is in git at
//! no revision. Every value assertion here is a claim about `b0c2a90e` plus an unbounded delta —
//! except where pi HARDCODES the value in `ai/scripts/generate-models.ts`, which is in git at
//! `v0.83.0`; those rows are pinned to the ported tag by the generator's `DELTAS` table, and each
//! one is named at its assertion.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use crate::collection::{CreateModelsOptions, Models, create_models};
use crate::{Model, all_providers};

// ------------------------------------------------------------------- the silent-emptiness guard --

/// The catalog directory, resolved at TEST time from `CARGO_MANIFEST_DIR`.
///
/// PROV-038: this replaces a hand-maintained `CATALOGS: &[(&str, &str)]` of 30 `include_str!`ed
/// blobs whose roster guard was `assert_eq!(CATALOGS.len(), 30, "catalog roster drifted from the
/// file set")` — an array compared against its own literal length, which can never observe the
/// drift its message claims to detect. The directory held **35** files: `amazon-bedrock.json` (the
/// 109-row largest cyrup ships), `github-copilot.json`, `google-vertex.json`, `openai-codex.json`
/// and `openrouter-images.json` got no per-model field checks at all, and the last of those is an
/// images provider that no test touched. `include_str!` cannot take a glob, so the array is
/// replaced by a directory walk.
fn catalog_dir() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/providers/catalog")
}

/// Every `*.json` under `src/providers/catalog/`, as `(file stem, contents)`.
fn catalogs() -> Vec<(String, String)> {
    let mut out = Vec::new();
    let dir = catalog_dir();
    for entry in std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
    {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("utf-8 file stem")
            .to_string();
        let body = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        out.push((stem, body));
    }
    out.sort();
    assert!(!out.is_empty(), "no catalogs found under {}", dir.display());
    out
}

/// Catalogs that are NOT text-model providers and therefore have no row in `all_providers()`.
/// `openrouter-images` resolves through the separate images registry (`images/mod.rs:38`).
const IMAGES_CATALOGS: &[&str] = &["openrouter-images"];

/// The guard. Production loaders swallow a parse error into `Vec::default()`, so without this a
/// typo'd catalog ships as an empty provider. Here the error is surfaced verbatim — for EVERY file
/// present, not for a list someone remembered to extend.
///
/// Each file is parsed with **the type its own production loader uses**. That distinction is not a
/// nicety: pi types the image catalogs as
/// `ImagesModel<TApi> extends Omit<Model<Api>, "api" | "provider" | "reasoning" | "contextWindow" |
/// "maxTokens" | "compat">` (`packages/ai/src/types.ts:825-829` @v0.83.0), so an image row has no
/// `reasoning`, no `contextWindow` and no `maxTokens` **by design**. Parsing
/// `openrouter-images.json` as a text [`Model`] therefore fails on `missing field reasoning` while
/// the shipped data is exactly right — the file is loaded by
/// [`crate::images::openrouter_image_models`] (`images/mod.rs:634`) as
/// [`crate::images::ImagesModel`], never as [`Model`].
#[test]
fn every_embedded_catalog_parses_non_empty() {
    for (name, blob) in catalogs() {
        if IMAGES_CATALOGS.contains(&name.as_str()) {
            // The images half of the same guard: `openrouter_image_models()` also swallows a parse
            // error into `Vec::default()`, so it needs the identical treatment against its own type.
            let models: Vec<crate::images::ImagesModel> = serde_json::from_str(&blob)
                .unwrap_or_else(|e| panic!("images catalog {name}.json failed to parse: {e}"));
            assert!(
                !models.is_empty(),
                "images catalog {name}.json parsed to ZERO models"
            );
            for m in &models {
                assert!(!m.id.is_empty(), "{name}: empty model id");
                assert!(!m.base_url.is_empty(), "{name}: {} has empty baseUrl", m.id);
                // The field that replaces the text catalog's `contextWindow` as the row's reason to
                // exist: pi makes `output` REQUIRED on `ImagesModel` (`types.ts:828`), and a row
                // that emits nothing is unusable.
                assert!(!m.output.is_empty(), "{name}: {} declares no output", m.id);
            }
            continue;
        }
        let models: Vec<Model> = serde_json::from_str(&blob)
            .unwrap_or_else(|e| panic!("catalog {name}.json failed to parse: {e}"));
        assert!(!models.is_empty(), "catalog {name}.json parsed to ZERO models");
        for m in &models {
            assert!(!m.id.as_str().is_empty(), "{name}: empty model id");
            assert!(m.context_window > 0, "{name}: {} has zero contextWindow", m.id);
            // Azure is the one provider whose endpoint is per-deployment and therefore supplied by
            // the user at runtime — pi's generated catalog ships `baseUrl: ""` for all 42 entries
            // (`azure-openai-responses.models.ts` @ `91585d9a`). Everywhere else an empty baseUrl
            // means the request would go nowhere.
            if name != "azure-openai-responses" {
                assert!(!m.base_url.is_empty(), "{name}: {} has empty baseUrl", m.id);
            }
        }
    }
}

/// The parse-type split above is only load-bearing if the images catalog really is a shape the text
/// [`Model`] rejects — otherwise the `continue` is silently covering nothing. This pins the split
/// itself: `openrouter-images.json` MUST fail as `Vec<Model>` (pi omits `reasoning` from
/// `ImagesModel`, `types.ts:825-829`) and MUST succeed as `Vec<ImagesModel>` with the same row count
/// the production loader hands the provider.
#[test]
fn the_images_catalog_is_an_images_shape_not_a_model_shape() {
    let (_, blob) = catalogs()
        .into_iter()
        .find(|(name, _)| name == "openrouter-images")
        .expect("openrouter-images.json is shipped");

    let as_text = serde_json::from_str::<Vec<Model>>(&blob)
        .expect_err("an images row has no `reasoning`/`contextWindow`/`maxTokens` — pi omits them");
    assert!(
        as_text.to_string().contains("reasoning"),
        "expected the missing text-only field to be named, got {as_text}"
    );

    let as_images: Vec<crate::images::ImagesModel> =
        serde_json::from_str(&blob).expect("parses as the type its loader uses");
    assert_eq!(
        as_images.len(),
        crate::images::openrouter_image_models().len(),
        "the loader must not be silently defaulting to an empty catalog"
    );
}

/// PROV-038, roster half: the set of catalog file stems must equal the registered provider ids plus
/// the images providers. Adding a sixth catalog without registering its provider now FAILS, which
/// is the drift the old tautological `CATALOGS.len() == 30` claimed to detect and could not.
#[test]
fn the_catalog_file_set_matches_the_registered_providers() {
    let mut on_disk: Vec<String> = catalogs().into_iter().map(|(name, _)| name).collect();
    on_disk.sort();
    let mut expected: Vec<String> = all_providers()
        .iter()
        .map(|p| p.id().as_str().to_string())
        .chain(IMAGES_CATALOGS.iter().map(|s| (*s).to_string()))
        .collect();
    // Several providers share one catalog file or ship none of their own; only assert that every
    // FILE has an owner, and that every registered provider that ships a file is present.
    expected.sort();
    expected.dedup();
    for name in &on_disk {
        assert!(
            expected.contains(name),
            "catalog {name}.json has no registered provider and is not an images catalog — \
             register it in providers/all.rs or delete the file"
        );
    }
}

/// PROV-030's regression guard (PROV-038 asked for it here): every row's `api` must be an api the
/// registry can actually construct, otherwise the model resolves, lists in `/model`, and then dies
/// at `wire.rs` with `no API implementation for <api>`.
///
/// **There is no carve-out, and there must never be one again.** `google-vertex` was the single
/// dangling api this guard was written around; `api/google_vertex.rs` closed it (PROV-030) and the
/// `KNOWN_DANGLING` exemption list was deleted in the same change, as the guard's own instructions
/// required. A fresh dangling api on any provider now fails here immediately — which is exactly what
/// would have stopped PROV-030 shipping.
#[test]
fn every_catalog_row_names_a_registered_api() {
    let registry = crate::api::builtin_registry();
    for (name, blob) in catalogs() {
        if IMAGES_CATALOGS.contains(&name.as_str()) {
            continue; // resolved through the images registry, not the text one
        }
        let models: Vec<Model> = serde_json::from_str(&blob).unwrap_or_default();
        for m in &models {
            assert!(
                registry.contains(&m.api),
                "{name}: {} names api `{}`, which register_builtins() does not provide — \
                 every request on this row would die with `no API implementation for {}`",
                m.id,
                m.api,
                m.api
            );
        }
    }
}

/// PROV-039: the manifest's own note counts the embedded catalogs, and its `generatedAt` is the
/// pi.dev overlay's staleness floor (`providers/all.rs:95` → `remote_catalog.rs:188-196`). Both
/// drifted from the file set; this pins them together so the next refresh cannot repeat it.
#[test]
fn the_catalog_manifest_matches_the_file_set() {
    let raw = include_str!("../providers/catalog_manifest.json");
    let manifest: serde_json::Value = serde_json::from_str(raw).expect("manifest parses");
    let note = manifest["note"].as_str().expect("note");
    let count = catalogs().len();
    assert!(
        note.contains(&format!("{count} embedded catalogs")),
        "the manifest note must state the real catalog count ({count}): {note}"
    );
    // The floor must be the LATEST extraction revision. b0c2a90e (2026-07-17T09:00:03Z) is the
    // newest any embedded catalog was taken from — see providers/google_vertex.rs's provenance
    // note — so an overlay dated between 2026-07-10 and that must be DISCARDED, not accepted.
    let generated_at = crate::providers::all::builtin_model_data_generated_at()
        .expect("generatedAt parses");
    let jul_17 = 1_784_278_803_000_i64; // 2026-07-17T09:00:03Z
    assert_eq!(generated_at, jul_17, "the floor must be b0c2a90e's timestamp");
}

/// The same guard one level up: every *registered* provider must expose a non-empty catalog. Catches
/// a loader wired to the wrong file as well as a bad blob.
#[test]
fn every_registered_provider_has_a_non_empty_catalog() {
    for p in all_providers() {
        assert!(
            !p.models().is_empty(),
            "provider {} exposes zero models — catalog parse likely failed silently",
            p.id()
        );
    }
}

// -------------------------------------------------------------------------- the selection seam --

/// `Models::get_model` (collection.rs:108) is cyrup's port of pi `models.getModel` — the lookup
/// every consumer performs to turn a `provider/id` pair into the `Model` that shapes the request.
/// Asserting through it (rather than against the raw JSON) proves the corrected value actually
/// *reaches model selection*.
fn selection() -> Models {
    let mut models = create_models(CreateModelsOptions::default());
    for p in all_providers() {
        models.set_provider(p);
    }
    models
}

fn pick(models: &Models, provider: &str, id: &str) -> Model {
    models
        .get_model(provider, id)
        .unwrap_or_else(|| panic!("model selection could not find {provider}/{id}"))
}

// ------------------------------------------------------------------------------ the headline case --

/// **The headline PROV-004 case.** Anthropic shipped a 1M-token context for Sonnet 4.5; pi picked it
/// up in `cc2db980` (`anthropic.models.ts:185-201` and `:202-218` @ `91585d9a` both read
/// `contextWindow: 1000000`). cyrup's snapshot still capped it at 200k, so compaction triggered ~5x
/// too early and the user could not use four fifths of the window they were paying for.
/// `maxTokens` was already correct at 64000 and must not move.
#[test]
fn sonnet_4_5_offers_the_full_1m_context_window() {
    let models = selection();
    for id in ["claude-sonnet-4-5", "claude-sonnet-4-5-20250929"] {
        let m = pick(&models, "anthropic", id);
        assert_eq!(
            m.context_window, 1_000_000,
            "{id}: pi anthropic.models.ts @91585d9a says contextWindow 1000000 (cc2db980)"
        );
        assert_eq!(m.max_tokens, 64_000, "{id}: maxTokens is unchanged at 64000");
    }
}

/// `claude-sonnet-4-6` doubled its output cap. pi `anthropic.models.ts:235` @ `91585d9a`:
/// `maxTokens: 128000`. cyrup capped generation at 64000, silently truncating long outputs.
#[test]
fn sonnet_4_6_max_tokens_is_128k() {
    let m = pick(&selection(), "anthropic", "claude-sonnet-4-6");
    assert_eq!(m.max_tokens, 128_000);
    assert_eq!(m.context_window, 1_000_000);
}

// ------------------------------------------------------------------- retired / added model sets --

/// `cc2db980` moved generation to models.dev's per-provider catalogs, which do not list EOL models;
/// ten Claude 3.x/4.0 entries were dropped from `anthropic.models.ts` in that commit. Offering a
/// retired model is worse than not offering it: selection succeeds and the API call then fails.
#[test]
fn retired_claude_models_are_gone() {
    let models = selection();
    for id in [
        "claude-3-5-sonnet-20240620",
        "claude-3-5-sonnet-20241022",
        "claude-3-7-sonnet-20250219",
        "claude-3-haiku-20240307",
        "claude-3-opus-20240229",
        "claude-3-sonnet-20240229",
        "claude-opus-4-0",
        "claude-opus-4-20250514",
        "claude-sonnet-4-0",
        "claude-sonnet-4-20250514",
    ] {
        assert!(
            models.get_model("anthropic", id).is_none(),
            "{id} was retired upstream in cc2db980 but is still selectable"
        );
    }
    // …and the surviving set is exactly pi's 14.
    assert_eq!(models.get_models(Some("anthropic")).len(), 14);
    // Every remaining Claude model is a reasoning model (pi @91585d9a: all 14 `reasoning: true`).
    assert!(models.get_models(Some("anthropic")).iter().all(|m| m.reasoning));
}

/// Models pi added in the missed window that cyrup users simply could not select. Sources:
/// `xai.models.ts` (grok-4.5), `openai.models.ts` + `azure-openai-responses.models.ts` (`7df2a94e`,
/// GPT-5.6 luna/sol/terra), `cerebras.models.ts`, `huggingface.models.ts` (`cc2db980`),
/// `nvidia.models.ts`, `opencode.models.ts`, `vercel-ai-gateway.models.ts` — all @ `91585d9a`.
#[test]
fn models_added_upstream_are_now_selectable() {
    let models = selection();
    let expect = [
        ("xai", "grok-4.5"),
        ("openai", "gpt-5.6-luna"),
        ("openai", "gpt-5.6-sol"),
        ("openai", "gpt-5.6-terra"),
        ("azure-openai-responses", "gpt-5.6-luna"),
        ("cerebras", "gemma-4-31b"),
        ("huggingface", "openai/gpt-oss-20b"),
        ("nvidia", "z-ai/glm-5.2"),
        ("opencode", "claude-fable-5"),
        ("opencode", "grok-4.5"),
        ("opencode", "hy3-free"),
        ("vercel-ai-gateway", "anthropic/claude-fable-5"),
        ("vercel-ai-gateway", "xai/grok-4.5"),
        ("openrouter", "x-ai/grok-4.5"),
        ("openrouter", "openai/gpt-5.6-luna"),
        ("openrouter", "tencent/hy3"),
    ];
    for (provider, id) in expect {
        assert!(
            models.get_model(provider, id).is_some(),
            "{provider}/{id} exists upstream @91585d9a but is not selectable"
        );
    }
    // nvidia replaced GLM 5.1 with 5.2; openrouter renamed the poolside ids.
    assert!(models.get_model("nvidia", "z-ai/glm-5.1").is_none());
    assert!(models.get_model("openrouter", "poolside/laguna-xs.2").is_none());
    assert!(models.get_model("openrouter", "poolside/laguna-xs-2.1").is_some());
}

// ------------------------------------------------------------------------------- cost / capability --

/// `mistral-medium-latest` was mis-described on **two** axes at once: cyrup said it cannot reason
/// and billed it at roughly a quarter of its real rate. pi `mistral.models.ts` @ `91585d9a`
/// (changed by `cc2db980`): `reasoning: true`, `cost {input 1.5, output 7.5, cacheRead 0.15}`.
/// `reasoning: false` also suppresses the thinking UI for a model that supports it.
#[test]
fn mistral_medium_reasons_and_is_priced_correctly() {
    let m = pick(&selection(), "mistral", "mistral-medium-latest");
    assert!(m.reasoning, "pi mistral.models.ts @91585d9a: reasoning true");
    assert_eq!(m.cost.input, 1.5);
    assert_eq!(m.cost.output, 7.5);
    assert_eq!(m.cost.cache_read, 0.15);
}

/// Two cache-read rates were wrong by ~2x and 10x respectively. A wrong `cacheRead` does not break a
/// request — it silently misreports spend in the footer and in session cost accounting.
/// pi @ `91585d9a`: `fireworks.models.ts` glm-5p2 `cacheRead: 0.14` (`844d175e` aligned the pair);
/// `vercel-ai-gateway.models.ts` deepseek-v4-flash `cacheRead: 0.028`.
#[test]
fn cache_read_rates_match_upstream() {
    let models = selection();
    let fw = pick(&models, "fireworks", "accounts/fireworks/models/glm-5p2");
    assert_eq!(fw.cost.cache_read, 0.14, "cyrup over-reported this by 1.86x");

    let vercel = pick(&models, "vercel-ai-gateway", "deepseek/deepseek-v4-flash");
    assert_eq!(
        vercel.cost.cache_read, 0.028,
        "cyrup under-reported this by 10x (0.0028)"
    );
}

/// The Xiaomi *token-plan* providers are prepaid: usage is drawn from a plan, not billed per token,
/// so pi zeroes every rate. `cc2db980` also removed the API-billing-only models that had been cloned
/// into the token-plan catalogs (see that commit's own message naming `mimo-v2-omni`). cyrup billed
/// phantom dollars against a prepaid plan and offered two models the endpoint does not serve.
#[test]
fn xiaomi_token_plans_are_prepaid_and_carry_no_api_billing_models() {
    let models = selection();
    for provider in [
        "xiaomi-token-plan-ams",
        "xiaomi-token-plan-cn",
        "xiaomi-token-plan-sgp",
    ] {
        let list = models.get_models(Some(provider));
        assert!(!list.is_empty(), "{provider} has no models");
        for m in &list {
            assert_eq!(
                (m.cost.input, m.cost.output, m.cost.cache_read, m.cost.cache_write),
                (0.0, 0.0, 0.0, 0.0),
                "{provider}/{}: token-plan usage is prepaid, pi zeroes all rates",
                m.id
            );
        }
        for id in ["mimo-v2-omni", "mimo-v2.5-pro-ultraspeed"] {
            assert!(
                models.get_model(provider, id).is_none(),
                "{provider}/{id} is API-billing-only; cc2db980 removed it from the token plans"
            );
        }
    }
}

/// pi `46145bef` ("use context length from top provider") replaced OpenRouter's theoretical model
/// maxima with what the top serving provider actually accepts. cyrup's 10M for Llama 4 Scout was the
/// paper number; a request sized to it is rejected by the router. Same class of fix for the
/// `maxTokens` entries, which were the router's generic 4096/16384 defaults.
#[test]
fn openrouter_context_windows_come_from_the_serving_provider() {
    let models = selection();

    let scout = pick(&models, "openrouter", "meta-llama/llama-4-scout");
    assert_eq!(scout.context_window, 327_680, "not the 10M paper maximum");

    // `deepseek/deepseek-v4-flash` is the row that shows why a catalog assertion must name its
    // revision. It reads `maxTokens: 65536, contextWindow: 1048576` at `91585d9a` and
    // `maxTokens: 4096, contextWindow: 1048575` at `b0c2a90e` (`openrouter.models.ts`, both
    // revisions) — models.dev re-reads the top serving provider every refresh and this one moved
    // back within the week. The catalogs are generated from ONE revision (`b0c2a90e`, PROV-060), so
    // this asserts that revision's numbers; `scout` and `r1` above/below are the stable evidence
    // for `46145bef` itself.
    let flash = pick(&models, "openrouter", "deepseek/deepseek-v4-flash");
    assert_eq!(flash.max_tokens, 4_096, "openrouter.models.ts @b0c2a90e");
    assert_eq!(flash.context_window, 1_048_575, "openrouter.models.ts @b0c2a90e");

    let r1 = pick(&models, "openrouter", "deepseek/deepseek-r1");
    assert_eq!(r1.context_window, 64_000);

    // A transposed digit in the snapshot: 1048756 is not a power-of-two-ish window at all.
    let gem = pick(&models, "openrouter", "google/gemini-3.1-pro-preview-customtools");
    assert_eq!(gem.context_window, 1_048_576);
}

/// opencode-go's MiniMax M3 carried a marketing suffix cyrup's snapshot picked up and upstream
/// dropped (`opencode-go.models.ts` @ `91585d9a`: `name: "MiniMax-M3"`). Display-only, but the model
/// picker shows it.
#[test]
fn opencode_go_minimax_m3_display_name_matches_upstream() {
    let m = pick(&selection(), "opencode-go", "minimax-m3");
    assert_eq!(m.name, "MiniMax-M3");
}

// ------------------------------- fireworks GLM compat (PROV-061, superseded by DRIFT-052) --

/// **PROV-061, superseded by DRIFT-052 — the flags are back, and now they are SOURCED.**
///
/// PROV-061 removed `sendSessionAffinityHeaders: true` / `supportsLongCacheRetention: false` from
/// the two `openai-completions` rows in `fireworks.json` because pi carries NEITHER at either
/// provenance revision: `git show 91585d9a:packages/ai/src/providers/fireworks.models.ts` and
/// `git show b0c2a90e:...` both give `compat: {"supportsStore":false,"supportsDeveloperRole":false}`
/// for `accounts/fireworks/models/glm-5p2` (`:61-68`) and `accounts/fireworks/routers/glm-5p2-fast`
/// (`:224-231`). That call was correct **as provenance**: the block had been pattern-matched from
/// the fourteen `anthropic-messages` rows in the same file, with no citation behind it.
///
/// **DRIFT-052** re-derives the same two values from a citation rather than a pattern. pi
/// `b9497c8c1` ("fix(ai): correct Fireworks GLM prompt caching, closes #7676" — first tag
/// **v0.84.0**, unchanged at v0.84.2) replaced the inline `candidate.compat = { supportsStore:
/// false, supportsDeveloperRole: false }` assignment (v0.83.0 `ai/scripts/generate-models.ts:2151-2155`)
/// with the shared `openAICompat` constant `processFireworksModels` builds at v0.84.2 `:1239-1244`
/// — `{ supportsStore: false, supportsDeveloperRole: false, sendSessionAffinityHeaders: true,
/// supportsLongCacheRetention: false }` — applied to every `glm-5p2` row at `:1274-1280`. The
/// v0.83.0 shape is an upstream BUG, and #7676 is the report of it.
///
/// The values are not inert, in either direction. `openai-completions`' affinity gate is
/// `if (sessionId && compat.sendSessionAffinityHeaders)` (pi `api/openai-completions.ts:647`,
/// ported at `api/openai_completions.rs`), and `detect_compat` gives
/// `send_session_affinity_headers: false` for fireworks, so the catalog value alone decides it:
/// **without** the flag cyrup emits no `x-session-affinity` and every Fireworks prompt-cache
/// lookup misses, because Fireworks routes cache by replica affinity. Symmetrically,
/// `supports_long_cache_retention` detects to `true` for fireworks, so its absence makes cyrup ask
/// for a retention Fireworks does not honour.
///
/// The forward-port is carried by the generator, not by hand: `xtask/src/main.rs`'s `DELTAS` table
/// pins both rows (`WHY_FIREWORKS_GLM_COMPAT`), so `gen-catalogs --check` still reproduces the tree
/// and a future regeneration cannot silently revert it. This test now asserts the pinned values —
/// stated over the whole provider rather than the two ids, so a THIRD `openai-completions` row
/// appearing with the block copied onto it still fails here. The `anthropic-messages` rows are
/// deliberately excluded: `sendSessionAffinityHeaders: true` is upstream's value for all fourteen
/// of them for an unrelated reason.
#[test]
fn fireworks_openai_completions_rows_carry_pi_s_openai_compat() {
    let models = selection();
    let rows: Vec<Model> = models
        .get_models(Some("fireworks"))
        .into_iter()
        .filter(|m| m.api.as_str() == "openai-completions")
        .collect();

    assert_eq!(
        rows.len(),
        2,
        "fireworks ships exactly two openai-completions rows (glm-5p2, glm-5p2-fast); \
         if that changed, re-derive this test's scope against pi's fireworks.models.ts"
    );

    for m in rows {
        let compat = m
            .compat
            .as_ref()
            .unwrap_or_else(|| panic!("fireworks/{} lost its compat block entirely", m.id));
        assert_eq!(
            compat.send_session_affinity_headers,
            Some(true),
            "fireworks/{} must carry pi's openAICompat sendSessionAffinityHeaders: true \
             (generate-models.ts:1241 @v0.84.2, b9497c8c1); detect_compat gives false for \
             fireworks, so dropping it makes every Fireworks prompt-cache lookup miss",
            m.id
        );
        assert_eq!(
            compat.supports_long_cache_retention,
            Some(false),
            "fireworks/{} must carry pi's openAICompat supportsLongCacheRetention: false \
             (generate-models.ts:1243 @v0.84.2); detect_compat gives TRUE for fireworks, so \
             dropping it makes cyrup request a retention Fireworks does not honour",
            m.id
        );
        assert_eq!(
            compat.supports_store,
            Some(false),
            "fireworks/{} must keep pi's supportsStore: false",
            m.id
        );
        assert_eq!(
            compat.supports_developer_role,
            Some(false),
            "fireworks/{} must keep pi's supportsDeveloperRole: false",
            m.id
        );
    }
}

// ============================== the b0c2a90e regeneration (PROV-054 … PROV-060) ==============

// # The regeneration
//
// Everything below this line is a consequence of ONE change: `providers/catalog/*.json` and
// `catalog_manifest.json` are now generated by `cargo run -p xtask -- gen-catalogs` from a single
// pinned pi revision (`b0c2a90e`) instead of being a hand-taken snapshot split across two
// revisions (31 files at `91585d9a`, 4 at `b0c2a90e`). That split week is the root cause of
// PROV-054 … PROV-059: 25 models pi ships that cyrup lacked, 16 pi had retired that cyrup still
// offered, 20 rows missing a compat flag and 129 field differences.
//
// The premise that made this unauditable for nine sweeps — "pi gitignores the catalog data, so no
// per-field claim is checkable from a checkout" — is FALSE at `b0c2a90e`, the direct parent of
// `a9f6a3159` (`feat(ai): separate generated model data (#6765)`) and the revision the manifest
// already named. There the `*.models.ts` modules are full data literals. `git show` plus
// `xtask/src/tsdata.rs` recovers all of it with no generator run, no `npm install` and no network
// (PROV-060).
//
// **The residue, stated so nobody reads these tests as proof of parity at the ported tag:**
// `b0c2a90e` is 2026-07-17 and `v0.83.0` is 2026-07-30. The data for those 13 days is in git at no
// revision. Every assertion below is a claim about `b0c2a90e` plus an unbounded delta — EXCEPT
// where pi hardcodes the value in `ai/scripts/generate-models.ts`, which IS in git at `v0.83.0`;
// those rows are pinned to the ported tag by the generator's `DELTAS` table and are called out
// individually here.

/// **PROV-054 — the highest-severity row on this surface, and it is the protocol, not a flag.**
///
/// pi routes `xai/grok-4.5` over the Responses API: `XAI_RESPONSES_MODEL_ID = "grok-4.5"`
/// (`ai/scripts/generate-models.ts:378` @v0.83.0) selects it at `:1408`
/// (`const useResponsesApi = modelId === XAI_RESPONSES_MODEL_ID`) and gives it
/// `XAI_RESPONSES_COMPAT = { supportsLongCacheRetention: false }` (`:390-392`) plus
/// `XAI_RESPONSES_EFFORT_LEVEL_MAP = { off: null, minimal: null }` (`:386-389`). The generated
/// output agrees: `xai.models.ts:25-42` @`b0c2a90e` is `api: "openai-responses"`.
///
/// cyrup carried the pre-move row from `91585d9a`: `api: "openai-completions"`, the three old
/// `supportsStore`/`supportsDeveloperRole`/`supportsReasoningEffort` flags, no `thinkingLevelMap`
/// and no `supportsLongCacheRetention`. `WireProvider` dispatches on `model.api` (`wire.rs:215`),
/// so cyrup built a Chat-Completions body — `messages[]`, no `reasoning` object, a different SSE
/// grammar — and POSTed it to the Completions path for **the xai default model**
/// (`cyrup-config/src/model.rs:1075` maps `"xai" => "grok-4.5"`). Every request diverged wholesale.
///
/// Pre-fix this test is RED on all four assertions.
#[test]
fn xai_grok_4_5_is_routed_over_the_responses_api() {
    let models = selection();
    let m = pick(&models, "xai", "grok-4.5");

    assert_eq!(
        m.api.as_str(),
        "openai-responses",
        "grok-4.5 is the xai DEFAULT model; on openai-completions every request is the wrong \
         protocol, not merely the wrong flag"
    );

    // `thinkingLevelMap: {off: null, minimal: null}` — the two levels pi SUPPRESSES for this model.
    let map = m
        .thinking_level_map
        .as_ref()
        .expect("grok-4.5 carries pi's XAI_RESPONSES_EFFORT_LEVEL_MAP");
    assert_eq!(map.get("off"), Some(&None));
    assert_eq!(map.get("minimal"), Some(&None));
    assert_eq!(map.len(), 2, "pi maps exactly off and minimal");

    // `supportsLongCacheRetention: false`. Absent, the resolver's detector defaults it TRUE for
    // xai, so cyrup would offer a retention xAI rejects (`api/compat.rs`).
    let compat = crate::api::compat::get_responses_compat(&m);
    assert!(
        !compat.supports_long_cache_retention,
        "pi's XAI_RESPONSES_COMPAT sets supportsLongCacheRetention: false"
    );

    // MIRROR: the two rows either side of it stay on Completions, so this pins the per-row api and
    // not a whole-provider switch (`xai.models.ts:10` and `:47` @b0c2a90e).
    for id in ["grok-4.3", "grok-build-0.1"] {
        assert_eq!(
            pick(&models, "xai", id).api.as_str(),
            "openai-completions",
            "{id} is NOT the responses model"
        );
    }
}

/// **PROV-055 — the fourth instance of "wrong by default whenever the catalog is silent".**
///
/// pi builds every OpenCode Zen `@ai-sdk/openai` variant with
/// `compat = { sessionAffinityFormat: "openai-nosession" }`
/// (`ai/scripts/generate-models.ts:1666` @v0.83.0), and the Responses route's header gate is
/// `if (sessionId)` with NO `sendSessionAffinityHeaders` guard (`api/openai-responses.ts:232-241`)
/// — so the format ALONE decides the headers. cyrup's rows carried `compat: null`, and
/// `get_responses_compat` then falls back to `detect_session_affinity_format`
/// (`api/compat.rs:84-92`), which returns `Openai` for provider `opencode` — emitting a
/// `session_id` header pi deliberately suppresses, on every request that carries a session id.
///
/// The assertion is over EVERY `openai-responses` row of the provider rather than a fixed id list,
/// so a future row that arrives without the flag fails here too. Pre-fix: RED on all of them
/// (16 rows before the regeneration, 19 after — the GPT-5.6 trio is PROV-057).
#[test]
fn every_opencode_responses_row_suppresses_the_session_id_header() {
    use crate::api::compat::{SessionAffinityFormat, get_responses_compat};

    let models = selection();
    let rows: Vec<Model> = models
        .get_models(Some("opencode"))
        .into_iter()
        .filter(|m| m.api.as_str() == "openai-responses")
        .collect();

    assert_eq!(
        rows.len(),
        19,
        "opencode ships 19 openai-responses rows at b0c2a90e; if that moved, re-derive the scope \
         against pi's opencode.models.ts rather than loosening this test"
    );

    for m in &rows {
        assert_eq!(
            get_responses_compat(m).session_affinity_format,
            SessionAffinityFormat::OpenaiNosession,
            "opencode/{} resolves to the `openai` affinity format, so cyrup leaks a session_id \
             header to OpenCode Zen that pi suppresses",
            m.id
        );
    }

    // MIRROR: this is a per-row catalog value, not a provider-wide detection rule. The provider's
    // non-Responses rows are untouched by it, and the detector still answers `Openai` for opencode.
    let completions = models
        .get_models(Some("opencode"))
        .into_iter()
        .find(|m| m.api.as_str() == "openai-completions")
        .expect("opencode ships openai-completions rows too");
    assert_eq!(
        crate::api::compat::detect_session_affinity_format(&completions),
        SessionAffinityFormat::Openai,
        "the DETECTOR is unchanged — what fixed this is catalog data, not a new default"
    );
}

/// **PROV-056 — two wire divergences per request, on every model the provider has.**
///
/// pi constructs all three `kimi-coding` rows with `forceAdaptiveThinking: true` and adds
/// `allowEmptySignature: true` for the Kimi-For-Coding variants
/// (`ai/scripts/generate-models.ts:1861-1864` @v0.83.0); `kimi-coding.models.ts` @`b0c2a90e`
/// carries the same. cyrup had `compat: null` on all three.
///
/// `forceAdaptiveThinking` is read RAW off `model.compat`, not through a resolver
/// (`api/anthropic_messages.rs:349`, pi `api/anthropic-messages.ts:815`, `:858`, `:1033`), so
/// `get_anthropic_compat` is deliberately NOT the probe here — pi excludes the flag from its
/// resolver and cyrup correctly matches that. Pre-fix: RED on all four assertions.
#[test]
fn kimi_coding_rows_force_adaptive_thinking() {
    let models = selection();

    for id in ["k2p7", "kimi-k2-thinking", "kimi-for-coding"] {
        let m = pick(&models, "kimi-coding", id);
        let compat = m
            .compat
            .as_ref()
            .unwrap_or_else(|| panic!("kimi-coding/{id} has no compat block at all"));
        assert_eq!(
            compat.force_adaptive_thinking,
            Some(true),
            "kimi-coding/{id} sends a non-adaptive thinking block AND the \
             interleaved-thinking-2025-05-14 beta to an upstream pi flags as adaptive-only"
        );
    }

    // `allowEmptySignature` is per-row: without it cyrup converts empty-signature thinking blocks
    // to text instead of replaying `signature: ""` (pi `anthropic-messages.ts:967`), corrupting
    // thinking replay.
    assert_eq!(
        pick(&models, "kimi-coding", "kimi-for-coding")
            .compat
            .as_ref()
            .and_then(|c| c.allow_empty_signature),
        Some(true)
    );
    assert_eq!(
        pick(&models, "kimi-coding", "k2p7")
            .compat
            .as_ref()
            .and_then(|c| c.allow_empty_signature),
        None,
        "pi sets allowEmptySignature only on the Kimi-For-Coding variants"
    );
}

/// **PROV-057 — 25 model ids that resolve in pi and errored here.**
///
/// Every one is a row pi added between `91585d9a` and `b0c2a90e`, i.e. BEFORE the ported tag. This
/// is one provenance decision, not 25 bugs. Pre-fix: RED on all 25.
#[test]
fn every_model_the_regeneration_added_now_resolves() {
    let models = selection();
    const ADDED: &[(&str, &str)] = &[
        ("azure-openai-responses", "gpt-realtime-2.1"),
        ("cloudflare-ai-gateway", "gpt-5.6-luna"),
        ("cloudflare-ai-gateway", "gpt-5.6-sol"),
        ("cloudflare-ai-gateway", "gpt-5.6-terra"),
        ("cloudflare-ai-gateway", "workers-ai/@cf/zai-org/glm-5.2"),
        ("kimi-coding", "k3"),
        ("kimi-coding", "kimi-for-coding-highspeed"),
        ("moonshotai", "kimi-k3"),
        ("moonshotai-cn", "kimi-k3"),
        ("openai", "gpt-realtime-2.1"),
        ("opencode", "gpt-5.6-luna"),
        ("opencode", "gpt-5.6-sol"),
        ("opencode", "gpt-5.6-terra"),
        ("opencode-go", "grok-4.5"),
        ("opencode-go", "kimi-k3"),
        ("openrouter", "kwaipilot/kat-coder-air-v2.5"),
        ("openrouter", "kwaipilot/kat-coder-pro-v2.5"),
        ("openrouter", "meta/muse-spark-1.1"),
        ("openrouter", "moonshotai/kimi-k3"),
        ("vercel-ai-gateway", "anthropic/claude-opus-4.7-fast"),
        ("vercel-ai-gateway", "anthropic/claude-opus-4.8-fast"),
        ("vercel-ai-gateway", "kwaipilot/kat-coder-air-v2.5"),
        ("vercel-ai-gateway", "kwaipilot/kat-coder-pro-v2.5"),
        ("vercel-ai-gateway", "moonshotai/kimi-k3"),
        ("vercel-ai-gateway", "thinkingmachines/inkling"),
    ];
    assert_eq!(ADDED.len(), 25);
    for (provider, id) in ADDED {
        assert!(
            models.get_model(provider, id).is_some(),
            "{provider}/{id} resolves in pi @b0c2a90e and must resolve here"
        );
    }
}

/// **PROV-058 — 16 ids cyrup offered, autocompleted and would have billed, that pi had retired.**
///
/// The five xai rows are not models.dev churn: pi drops them by NAME through
/// `XAI_BUILTIN_EXCLUDED_MODEL_IDS` (`ai/scripts/generate-models.ts:379-385` @v0.83.0, applied at
/// `:2078`), so this half is confirmed at the PORTED TAG, not just at `b0c2a90e`. An id gone
/// upstream is usually gone at the vendor too, so the reachable outcome was a model that appears
/// in `/model`, is selectable, and then fails at the API. Pre-fix: RED on all 16.
#[test]
fn every_model_upstream_retired_is_gone() {
    let models = selection();
    const RETIRED: &[(&str, &str)] = &[
        ("xai", "grok-3"),
        ("xai", "grok-3-fast"),
        ("xai", "grok-4.20-0309-non-reasoning"),
        ("xai", "grok-4.20-0309-reasoning"),
        ("xai", "grok-code-fast-1"),
        ("vercel-ai-gateway", "anthropic/claude-3.5-haiku"),
        ("vercel-ai-gateway", "arcee-ai/trinity-large-preview"),
        ("vercel-ai-gateway", "meituan/longcat-flash-chat"),
        ("vercel-ai-gateway", "meituan/longcat-flash-thinking-2601"),
        ("vercel-ai-gateway", "mistral/devstral-small"),
        ("vercel-ai-gateway", "mistral/pixtral-large"),
        ("vercel-ai-gateway", "xiaomi/mimo-v2-flash"),
        ("vercel-ai-gateway", "xiaomi/mimo-v2-pro"),
        ("openrouter", "arcee-ai/trinity-mini"),
        ("openrouter", "liquid/lfm-2.5-1.2b-thinking:free"),
        ("openrouter", "openai/gpt-oss-120b:free"),
    ];
    assert_eq!(RETIRED.len(), 16);
    for (provider, id) in RETIRED {
        assert!(
            models.get_model(provider, id).is_none(),
            "{provider}/{id} was retired upstream before the ported tag and must not be offered"
        );
    }

    // The xai exclusion list is exhaustive: pi ships exactly three xai models.
    assert_eq!(models.get_models(Some("xai")).len(), 3);
}

/// **PROV-059 — the field differences are behavioural, not cosmetic.**
///
/// `cost` feeds `/session` and every usage total; `maxTokens` and `contextWindow` feed overflow
/// estimation and the compaction trigger. Each assertion below is one of the ledger's named worst
/// cases, and each was RED before the regeneration.
#[test]
fn the_regenerated_field_values_match_the_pinned_revision() {
    let models = selection();

    // (a) every kimi-coding session reported ZERO spend: all three rows were priced at 0/0/0/0.
    let k2p7 = pick(&models, "kimi-coding", "k2p7");
    assert_eq!(
        (k2p7.cost.input, k2p7.cost.output, k2p7.cost.cache_read),
        (0.95, 4.0, 0.19)
    );
    let thinking = pick(&models, "kimi-coding", "kimi-k2-thinking");
    assert_eq!(
        (
            thinking.cost.input,
            thinking.cost.output,
            thinking.cost.cache_read
        ),
        (0.6, 2.5, 0.15)
    );

    // (b) cerebras zai-glm-4.7 billed cached reads at zero (`cerebras.models.ts:55` @b0c2a90e).
    assert_eq!(
        pick(&models, "cerebras", "zai-glm-4.7").cost.cache_read,
        2.25
    );

    // opencode hy3-free overstated its window by 66k, deferring compaction past the real limit.
    assert_eq!(
        pick(&models, "opencode", "hy3-free").context_window,
        190_000
    );

    // openrouter carried 97 of the 129 differences; two representative ones, one per field class.
    assert_eq!(
        pick(&models, "openrouter", "anthropic/claude-sonnet-4").context_window,
        200_000,
        "the 1M window is the beta header's, not this row's"
    );
    assert_eq!(
        pick(&models, "openrouter", "openai/gpt-4o").cost.cache_read,
        1.25,
        "cached reads were billed at zero"
    );

    // vercel-ai-gateway's two Claude rows had maxTokens from a different model generation.
    assert_eq!(
        pick(&models, "vercel-ai-gateway", "anthropic/claude-opus-4").max_tokens,
        8_192
    );
}

/// **PROV-059(d) is REFUTED, and this test is the guard that keeps the refutation from being
/// regenerated away.**
///
/// The ledger reads `contextWindow: 372000` for the three Codex GPT-5.6 rows off `b0c2a90e` and
/// files cyrup's `272000` as a 100k understatement that "compacts 100k tokens early on all three".
/// It is the other way round. The Codex rows are **not** models.dev data — pi hardcodes them in
/// `ai/scripts/generate-models.ts`, which IS in git at the ported tag — and there
/// `CODEX_GPT_56_CONTEXT = 272000` at BOTH v0.83.0 (`:2352`) and v0.84.1 (`:2541`), with the
/// comment one line above at v0.83.0 (`:2349`) reading "GPT-5.6 follows Codex's 272k catalog limit
/// (**formerly 372k**)". `372000` is the former value, still present in `b0c2a90e`'s generated data
/// 13 days before the tag.
///
/// This is the one place where `b0c2a90e` is NOT the best source available, so the generator pins
/// the ported tag's value (`xtask/src/main.rs` `DELTAS`) and this asserts the pin holds.
#[test]
fn the_codex_gpt_5_6_context_window_stays_at_the_ported_tags_272k() {
    let models = selection();
    for id in ["gpt-5.6-luna", "gpt-5.6-sol", "gpt-5.6-terra"] {
        assert_eq!(
            pick(&models, "openai-codex", id).context_window,
            272_000,
            "{id}: b0c2a90e's 372000 is the value pi REPLACED before v0.83.0"
        );
    }
}

/// **PROV-060 — the manifest must describe a provenance the data actually has.**
///
/// Before the regeneration `generatedAt`/`source` named `b0c2a90e` while the note itself conceded
/// that 31 of the 35 files came from `91585d9a` — a drift guard reporting a floor the data did not
/// sit on. Now one revision generates every file, and the manifest records it per provider so the
/// claim is machine-checkable rather than prose.
#[test]
fn the_catalog_manifest_names_one_revision_per_provider() {
    let raw = include_str!("../providers/catalog_manifest.json");
    let manifest: serde_json::Value = serde_json::from_str(raw).expect("manifest parses");

    let source = manifest["source"].as_str().expect("source");
    assert_eq!(source, "pi@b0c2a90e");

    let per_provider = manifest["catalogs"]
        .as_object()
        .expect("PROV-060: the manifest carries a per-provider source map");
    assert_eq!(
        per_provider.len(),
        catalogs().len(),
        "every embedded catalog must name its source module"
    );
    for (name, entry) in per_provider {
        assert_eq!(
            entry["source"].as_str(),
            Some(source),
            "{name} names a different revision from the manifest's own — that split is exactly \
             what PROV-060 filed"
        );
        assert!(
            entry["module"]
                .as_str()
                .is_some_and(|m| m.starts_with("packages/ai/src/")),
            "{name} must name the upstream module it was extracted from"
        );
    }

    // The 13-day residue between b0c2a90e and the ported tag is unmeasurable, and the manifest —
    // not only the ledger — has to say so, because the manifest is what a future refresher reads.
    let note = manifest["note"].as_str().expect("note");
    assert!(
        note.contains("v0.83.0") && note.contains("NOT measurable"),
        "the manifest must record the irreducible 13-day residue (PROV-060): {note}"
    );

    // Every source module is one the generator actually knows how to read.
    assert!(
        per_provider["openrouter-images"]["module"]
            .as_str()
            .is_some_and(|m| m.ends_with("image-models.generated.ts")),
        "PROV-065: the images catalog has no *.models.ts counterpart and must not claim one"
    );
}

/// **PROV-018's drift check.** `#[ignore]`d because it needs a pi worktree on disk, which CI may
/// not have; run it with `cargo test -p cyrup-provider -- --ignored gen_catalogs` or, equivalently
/// and without cargo nesting, `cargo run -p xtask -- gen-catalogs --check`.
///
/// It fails the moment a catalog is hand-edited or the pinned revision moves — which is the guard
/// PROV-061 had to be closed without, and the reason the embedded data drifted a week behind its
/// own declared provenance for nine sweeps.
#[test]
#[ignore = "needs a pi worktree; run explicitly or via `cargo run -p xtask -- gen-catalogs --check`"]
fn gen_catalogs_check_reports_no_drift_against_the_pinned_revision() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root");
    let out = std::process::Command::new(env!("CARGO"))
        .current_dir(root)
        .args(["run", "--quiet", "-p", "xtask", "--", "gen-catalogs", "--check"])
        .output()
        .expect("cargo run -p xtask");
    assert!(
        out.status.success(),
        "the embedded catalogs no longer reproduce from the pinned pi revision:\n{}\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );
}
