//! The FROZEN CONTRACT for the inspector/project-pane subsystem — every type and error shared
//! across `actions`, `runner`, `herdr/` and `ghostty/`.
//!
//! This file is the score. It is written once, by the orchestrator, BEFORE any implementation, so
//! that modules written concurrently agree by construction rather than by reading each other's
//! half-finished files. **Implementations do not edit this file**; a change here is a change to
//! every consumer at once and is the orchestrator's call.
//!
//! Upstream: `src/inspectors/types.ts` (51 lines @v0.68.0) plus the error vocabularies of
//! `herdr/client.ts:3-9`, `herdr/focus.ts` and `herdr/project-panes.ts`.
//!
//! # How upstream's `isError` ports, once, here
//!
//! cyrup's [`ToolResult`](cyrup_core::ToolResult) has NO `isError` flag — the crate records this
//! at `extension/tool/routing.rs:991-992` and `:1551-1553`. Its error channel is
//! `Err(ToolError)`, which the runtime renders as an `is_error` tool result carrying the text.
//! So:
//!
//! | upstream | cyrup |
//! |---|---|
//! | `{ isError: true, content: [text] }` | `Err(ToolError::…)` whose `Display` IS that text |
//! | `{ isError: false, content: [text] }` | `Ok(ToolResult { content: vec![Content::text(…)], ..Default::default() })` |
//!
//! Three upstream messages LOOK like errors and are deliberately NOT (`actions.ts`,
//! `project-panes.ts`): *"No inspector plugin owns this binding…"* and the two
//! *"No Herdr project pane binding exists for …"*. Those are `Ok`, and a test pins each.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

// =================================================================================================
// The two shared literals — the argv token, and the header line the launch is VERIFIED by
// =================================================================================================

/// The `argv[1]` token that selects the in-pane inspector on the `cyrup` binary.
///
/// In the contract because it is written by one module and recognised by another: the launch
/// argv is built in [`super::actions::launch_for`], the dashboard it selects is rendered by
/// [`super::runner`], and `crates/cyrup/src/subagent_inspector_cmd.rs` is what dispatches on it in
/// the binary. It lived in `runner.rs` and was reached across those boundaries.
///
/// The SECOND independent literal of this token is that binary's own `SUBCOMMAND`, deliberately
/// not a shared import — the convention `background/spawn_detached.rs:82-85` states for
/// `__subagent-runner` and this follows it: "what the launch string contains" and "what `main`
/// recognizes" must each be free-standing enough to unit-test without depending on the other
/// crate's internals. `crates/cyrup-it/tests/subagents/inspector_runner_subcommand_integration.rs`
/// is the test that runs the real binary and proves the two agree.
///
/// The token is `__`-prefixed, absent from `--help` and absent from `subcommands::SUBCOMMANDS`, so
/// it is undiscoverable rather than absent — the same `[CYRUP-DELTA] (SEAM-109)` premise
/// `crates/cyrup/src/subagent_runner_cmd.rs:28-48` already records, now true of TWO tokens.
pub const INSPECTOR_SUBCOMMAND: &str = "__subagent-inspector";

/// The first token of the dashboard's header line, `"cyrup-inspector for "`.
///
/// The line itself is upstream's `pi-subagents inspector for ${status.runId}`
/// (`inspector-runner.ts:33`) under cyrup's own product name — the mandate's "pi names can change;
/// it's the features that matter".
///
/// Use [`inspector_header_line`] rather than this constant wherever a whole line is wanted; see
/// there for why.
pub const INSPECTOR_HEADER_PREFIX: &str = "cyrup-inspector for ";

/// The dashboard's first line for `run_id` — **rendered by the runner and matched by the herdr
/// backend, from this one function.**
///
/// This is the sharpest coupling in the subsystem, and it is in the contract because it spans two
/// implementation modules that never call each other:
///
/// * [`super::runner::format_inspector_dashboard`] makes this the dashboard's first line;
/// * [`super::herdr::actions::inspector_ready_marker`] feeds it to
///   `herdr pane wait-output <id> --match …`, which is how `inspector.open` confirms the pane
///   actually started the inspector before it writes a binding.
///
/// **If the two ever spell it differently, every `inspector.open` times out** (the wait runs for
/// `INSPECTOR_READY_TIMEOUT_MS`), closes the pane it just opened, and writes nothing — and NO unit
/// test in this subtree notices, because each one scripts the `wait-output` answer. That is not
/// hypothetical: a hand-written literal on this branch read `subagents inspector for {runId}`,
/// which is not a substring of the line the runner prints.
///
/// One function is what makes the drift impossible rather than merely detectable: a change to the
/// spelling moves both halves, and a half that stops calling this is a compile error at its own
/// call site rather than a five-second timeout in front of a user. `INSPECTOR_HEADER_PREFIX` stays
/// public for the `starts_with` assertions that check the PREFIX alone.
#[must_use]
pub fn inspector_header_line(run_id: &str) -> String {
    format!("{INSPECTOR_HEADER_PREFIX}{run_id}")
}

// =================================================================================================
// Verb vocabularies
// =================================================================================================

/// The four `inspector.*` verbs (pi `INSPECTOR_ACTIONS`, `subagent-executor.ts`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InspectorAction {
    /// `inspector.open`
    Open,
    /// `inspector.command`
    Command,
    /// `inspector.status`
    Status,
    /// `inspector.close`
    Close,
}

/// The three `project.*` verbs (pi `HERDR_PROJECT_PANE_ACTIONS`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectPaneAction {
    /// `project.open`
    Open,
    /// `project.status`
    Status,
    /// `project.close`
    Close,
}

impl InspectorAction {
    /// The wire spelling, as it appears in `SUBAGENT_ACTIONS`.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Open => "inspector.open",
            Self::Command => "inspector.command",
            Self::Status => "inspector.status",
            Self::Close => "inspector.close",
        }
    }

    /// Parse the wire spelling.
    #[must_use]
    pub fn from_wire(raw: &str) -> Option<Self> {
        match raw {
            "inspector.open" => Some(Self::Open),
            "inspector.command" => Some(Self::Command),
            "inspector.status" => Some(Self::Status),
            "inspector.close" => Some(Self::Close),
            _ => None,
        }
    }

    /// Whether the verb is in `MUTATING_MANAGEMENT_ACTIONS` (`subagent-executor.ts:213`) and so
    /// must pass the authority gate. `open`/`close` mutate; `command`/`status` do not.
    #[must_use]
    pub const fn is_mutating(self) -> bool {
        matches!(self, Self::Open | Self::Close)
    }
}

impl ProjectPaneAction {
    /// The wire spelling.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Open => "project.open",
            Self::Status => "project.status",
            Self::Close => "project.close",
        }
    }

    /// Parse the wire spelling.
    #[must_use]
    pub fn from_wire(raw: &str) -> Option<Self> {
        match raw {
            "project.open" => Some(Self::Open),
            "project.status" => Some(Self::Status),
            "project.close" => Some(Self::Close),
            _ => None,
        }
    }

    /// `open`/`close` mutate; `status` does not.
    #[must_use]
    pub const fn is_mutating(self) -> bool {
        matches!(self, Self::Open | Self::Close)
    }
}

// =================================================================================================
// Error vocabularies — `as_str` emits upstream's SCREAMING_SNAKE spellings VERBATIM, because they
// appear inside model-visible sentences: `Herdr inspector error ({code}): {message}` and
// `Herdr project pane error ({code}): {message}`.
// =================================================================================================

/// pi `HerdrErrorCode` (`herdr/client.ts:3-9`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HerdrErrorCode {
    /// `HERDR_UNAVAILABLE`
    Unavailable,
    /// `HERDR_UNSUPPORTED_VERSION`
    UnsupportedVersion,
    /// `PANE_GONE`
    PaneGone,
    /// `NOT_FOUND`
    NotFound,
    /// `TIMEOUT`
    Timeout,
    /// `VALIDATION_ERROR`
    ValidationError,
}

impl HerdrErrorCode {
    /// Upstream's spelling, verbatim.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Unavailable => "HERDR_UNAVAILABLE",
            Self::UnsupportedVersion => "HERDR_UNSUPPORTED_VERSION",
            Self::PaneGone => "PANE_GONE",
            Self::NotFound => "NOT_FOUND",
            Self::Timeout => "TIMEOUT",
            Self::ValidationError => "VALIDATION_ERROR",
        }
    }

    /// pi `normalizeCode` (`herdr/client.ts:35-41`) — a lowercase-contains ladder over whatever
    /// the backend sent, falling through to `ValidationError`. LOSSY by design: do not
    /// "improve" it into an exact match, because upstream's own callers depend on the ladder.
    #[must_use]
    pub fn from_wire_lossy(raw: &str) -> Self {
        let code = raw.to_ascii_lowercase();
        if code.contains("timeout") || code.contains("timed_out") {
            Self::Timeout
        } else if code.contains("gone") {
            Self::PaneGone
        } else if code.contains("not_found") || code.contains("not-found") || code == "no_such_pane"
        {
            Self::NotFound
        } else {
            Self::ValidationError
        }
    }
}

/// pi's focus-path codes (`herdr/focus.ts`) — a herdr code, or one of focus's own two.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HerdrFocusErrorCode {
    /// Any [`HerdrErrorCode`], passed through unchanged.
    Herdr(HerdrErrorCode),
    /// `PANE_FOCUS_UNSUPPORTED`
    PaneFocusUnsupported,
    /// `INVALID_PANE_RESPONSE`
    InvalidPaneResponse,
}

/// pi's project-pane codes (`herdr/project-panes.ts`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectPaneErrorCode {
    /// Any [`HerdrErrorCode`], passed through unchanged.
    Herdr(HerdrErrorCode),
    /// `INVALID_PROJECT_ROOT`
    InvalidProjectRoot,
    /// `INVALID_PANE_RESPONSE`
    InvalidPaneResponse,
    /// `INVALID_BINDING`
    InvalidBinding,
    /// `BINDING_READ_FAILED`
    BindingReadFailed,
    /// `BINDING_WRITE_FAILED`
    BindingWriteFailed,
    /// `BINDING_REMOVE_FAILED`
    BindingRemoveFailed,
    /// `PANE_FOCUS_UNSUPPORTED`
    PaneFocusUnsupported,
    /// `PANE_NOT_IDLE`
    PaneNotIdle,
    /// `PANE_OWNERSHIP_UNVERIFIED`
    PaneOwnershipUnverified,
}

impl HerdrFocusErrorCode {
    /// Upstream's spelling, verbatim.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Herdr(code) => code.as_str(),
            Self::PaneFocusUnsupported => "PANE_FOCUS_UNSUPPORTED",
            Self::InvalidPaneResponse => "INVALID_PANE_RESPONSE",
        }
    }
}

impl ProjectPaneErrorCode {
    /// Upstream's spelling, verbatim.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Herdr(code) => code.as_str(),
            Self::InvalidProjectRoot => "INVALID_PROJECT_ROOT",
            Self::InvalidPaneResponse => "INVALID_PANE_RESPONSE",
            Self::InvalidBinding => "INVALID_BINDING",
            Self::BindingReadFailed => "BINDING_READ_FAILED",
            Self::BindingWriteFailed => "BINDING_WRITE_FAILED",
            Self::BindingRemoveFailed => "BINDING_REMOVE_FAILED",
            Self::PaneFocusUnsupported => "PANE_FOCUS_UNSUPPORTED",
            Self::PaneNotIdle => "PANE_NOT_IDLE",
            Self::PaneOwnershipUnverified => "PANE_OWNERSHIP_UNVERIFIED",
        }
    }
}

// =================================================================================================
// Dispositions — typed where upstream returns a bare string or boolean
// =================================================================================================

/// Whether a pane herdr reports is provably the one this binding names
/// (`project-panes.ts` `projectPaneOwnership`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PaneOwnership {
    /// The pane's identity matched the binding.
    Verified,
    /// herdr could not tell — the public API refuses on this, the model-facing verbs tolerate it.
    Unknown,
    /// The pane exists but is someone else's.
    Mismatch,
}

/// A project pane's state as `project.status` reports it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectPaneState {
    /// No binding on disk.
    Absent,
    /// A binding, and herdr still has the pane.
    Open,
    /// A binding whose pane herdr no longer has.
    Stale,
}

/// What `open` actually did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpenDisposition {
    /// A new pane was created.
    Opened,
    /// The binding's pane was already live; it was focused, not duplicated.
    AlreadyOpen,
}

/// What `close` actually did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CloseDisposition {
    /// The pane was closed.
    Closed,
    /// There was nothing to close — NOT an error (see the module doc).
    Absent,
    /// The pane was already gone; only the stale binding was removed.
    StaleBindingRemoved,
}

/// The two branches of `formatShellCommand` (`shell_command.ts`), injectable so both are testable
/// on either host.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    /// PowerShell quoting.
    Win32,
    /// POSIX quoting.
    Unix,
}

// =================================================================================================
// The context an inspector plugin is handed
// =================================================================================================

/// Which run, and which child of it, a verb is about.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InspectorTarget {
    /// The async run id.
    pub run_id: String,
    /// The run's async directory.
    pub async_dir: PathBuf,
    /// The child index, when the verb named one.
    pub child_index: Option<usize>,
}

/// Everything a plugin may read. Constructed once per verb by `actions::build_context`.
#[derive(Debug, Clone)]
pub struct InspectorContext {
    /// The run this verb is about.
    pub target: InspectorTarget,
    /// The directory the inspector may be launched in — already validated by `trusted_dir`.
    pub trusted_dir: PathBuf,
    /// The mission backing this run, when one was resolved.
    pub mission_id: Option<String>,
    /// That mission's file.
    pub mission_path: Option<PathBuf>,
    /// The environment a backend's `available()` reads — pi's `context.env`, filled from
    /// `deps.env ?? process.env` (`actions.ts:126`).
    ///
    /// **This is the gate both built-in backends are.** herdr's is
    /// `env.HERDR_ENV === "1" && env.HERDR_PANE_ID?.trim()` (`herdr/plugin.ts:13-14`); ghostty's is
    /// `env.TERM_PROGRAM?.toLowerCase() === "ghostty"` (`ghostty/plugin.ts:13`). Neither probes,
    /// spawns or opens a socket, which is why `inspector.open` on a box with neither installed
    /// refuses in microseconds instead of hanging.
    ///
    /// It is on the CONTEXT rather than on each plugin because the dispatcher is what decides
    /// which backend runs. Each backend used to carry its own `with_env`, which works for a unit
    /// test of that backend and leaves the interesting path — *"nothing is installed, so
    /// `inspector.open` answers `NO_INSPECTOR_PLUGIN_AVAILABLE` and writes nothing"* — impossible
    /// to drive through [`super::actions::handle_inspector_action`], because nothing there could
    /// reach the plugins' private fields.
    ///
    /// A [`std::collections::BTreeMap`] rather than a trait object so the context stays `Clone` and
    /// `Debug`; it is also [`cyrup_herdr::EnvSource`] (`crates/cyrup-herdr/src/env.rs:51-55`), so
    /// `HerdrPane::discover` reads it directly and the workspace keeps ONE spelling of herdr's
    /// two-variable gate.
    pub env: std::collections::BTreeMap<String, String>,
}

/// The command an inspector host should run, and the roots it needs — what `inspector.command`
/// returns as text and what `open` hands its plugin.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InspectorLaunch {
    /// The executable.
    pub exe: String,
    /// Its arguments, including the base64 `--session-roots`.
    pub args: Vec<String>,
    /// The rendered one-line form, platform-quoted.
    pub display_command: String,
}

/// Caller-supplied knobs, straight off the tool params.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct InspectorParams {
    /// An explicit pane/window to reuse, when the caller named one.
    pub pane_id: Option<String>,
    /// Whether to focus the pane after opening.
    pub focus: Option<bool>,
}

/// The output of a spawned helper process (`ghostty`'s `osascript`, herdr's CLI fallback).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommandOutput {
    /// Captured stdout, already truncated to the caller's cap.
    pub stdout: String,
    /// Captured stderr, likewise.
    pub stderr: String,
    /// The process's exit code, when it exited rather than being signalled.
    pub exit_code: Option<i32>,
}

// =================================================================================================
// On-disk records — SHARED WITH PI, so keys do not change and unknown keys SURVIVE
// =================================================================================================

/// `schemaVersion: 1` as a validating newtype: it serialises as `1` and refuses anything else, so
/// a future version is a parse error rather than a silently mis-read record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SchemaVersion1;

impl Serialize for SchemaVersion1 {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_u8(1)
    }
}

impl<'de> Deserialize<'de> for SchemaVersion1 {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = u64::deserialize(deserializer)?;
        if value == 1 {
            Ok(Self)
        } else {
            Err(serde::de::Error::custom(format!(
                "unsupported inspector binding schemaVersion {value}, expected 1"
            )))
        }
    }
}

/// `kind: "herdr-inspector"` as a one-variant enum, for the same reason.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum HerdrInspectorKind {
    /// The only value.
    #[default]
    #[serde(rename = "herdr-inspector")]
    HerdrInspector,
}

/// The binding written at `<async_dir>/inspectors/herdr{,-<index>}.json`.
///
/// **No `deny_unknown_fields`, and that is deliberate**: this file is shared with pi, whose own
/// `parse` (`herdr/actions.ts:28-40`) validates only the REQUIRED keys and passes the rest
/// through. `#[serde(flatten)] extra` is what makes a cyrup round-trip preserve a key pi added —
/// `focus` rewrites the binding (`project-panes.ts:529-531`), so a struct that dropped unknown
/// keys would be silent data loss.
///
/// `skip_serializing_if` is required, not cosmetic: upstream's conditional spreads
/// (`herdr/actions.ts:122-126`) omit absent keys entirely, and a `"childIndex": null` would fail
/// pi's own check — `null` is not `undefined`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HerdrInspectorBinding {
    /// Always `1`.
    pub schema_version: SchemaVersion1,
    /// Always `"herdr-inspector"`.
    pub kind: HerdrInspectorKind,
    /// The run this pane inspects.
    pub run_id: String,
    /// That run's async directory.
    pub async_dir: PathBuf,
    /// The child index, when the binding is for one child.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub child_index: Option<usize>,
    /// The mission backing the run.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mission_id: Option<String>,
    /// That mission's file.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mission_path: Option<PathBuf>,
    /// The herdr pane holding the inspector.
    pub pane_id: String,
    /// ISO-8601 open time.
    pub opened_at: String,
    /// ISO-8601 last focus, when it has been focused.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_focused_at: Option<String>,
    /// The herdr version that opened it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub herdr_version: Option<String>,
    /// The command the pane runs.
    pub command: String,
    /// Every key this build does not know, preserved verbatim.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One roster row's worth of project pane (`HerdrProjectPaneSnapshot`, `shared/types.ts`).
///
/// **In the contract because it is SHARED, and by more modules than the one that builds it.**
/// `inspectors/herdr/project_panes.rs` produces one; `extension/executor/mod.rs` keeps the live
/// map of them (`SubagentExecutor::herdr_project_pane_map`, threaded into the `project.*` handler
/// and written through by `open`/`status`/`close`); `tui/fleet_state.rs` carries them on
/// [`crate::tui::fleet_state::FleetState`]; `tui/fleet_status.rs`'s `project_pane_entries` renders
/// them, and `crate::tui::fleet_status::FleetStatusEntry` holds one. It was declared in
/// `project_panes.rs` and reached across all of those boundaries.
///
/// `Eq` as well as `PartialEq`: every field is itself `Eq` (paths, strings, `bool`, `i64` and the
/// two enums above — no floats anywhere), and `FleetStatusEntry` derives `Eq` itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HerdrProjectPaneSnapshot {
    /// The root.
    pub project_root: PathBuf,
    /// Where its binding lives.
    pub binding_path: PathBuf,
    /// The pane.
    pub pane_id: String,
    /// ISO-8601 open time.
    pub opened_at: String,
    /// ISO-8601 last focus.
    pub last_focused_at: Option<String>,
    /// What the last look found.
    pub state: ProjectPaneState,
    /// herdr's agent status, lowercased.
    pub agent_status: String,
    /// Whether the pane is provably this binding's.
    pub ownership: PaneOwnership,
    /// Whether a `project.close` would be allowed right now.
    pub safe_to_close: bool,
    /// Epoch millis of the look this snapshot came from.
    pub refreshed_at: i64,
    /// The roster's one-line summary.
    pub summary: Option<String>,
    /// Its tab.
    pub tab_id: Option<String>,
    /// Its workspace.
    pub workspace_id: Option<String>,
    /// Its terminal title.
    pub terminal_title: Option<String>,
    /// Why the pane is stale, when it is.
    pub stale_reason: Option<String>,
}

/// The map a session keeps of every project pane it knows about, keyed by project root.
///
/// The session's one live instance is `SubagentExecutor::herdr_project_panes`; the `project.*`
/// handler writes through it and both readers above project from it.
pub type ProjectPaneSnapshots = std::collections::BTreeMap<PathBuf, HerdrProjectPaneSnapshot>;
