//! Where the bundled prompt/skill tree lives at run time (FLUX-001).
//!
//! The tree itself is EMBEDDED ([`crate::bundle`], generated by `build.rs`); what this module
//! decides is the directory the resource loader is pointed at. Before FLUX-001 that was
//! `env!("CARGO_MANIFEST_DIR")/resources` — the absolute source path of the BUILD machine — so
//! any binary run without that tree present (a release artifact, a container image, a cleaned
//! `cargo install` source dir) lost the fifteen `/flux/*` templates and the skill, silently.
//! Upstream never resolves a source path at run time: `flux_bootstrap/installer.py` @v0.0.40
//! copies its package data into `~/.code_puppy` at startup (`register_callbacks.py:47-71`).
//!
//! [`BundledRoot`] is decided ONCE, at construction (`crate::flux_extension`), from the two inputs
//! that determine it — the agent dir the binary already resolved for every other extension and
//! the `CYRUP_FLUX_RESOURCES_DIR` override — and `ResourcesDiscover` then only asks it for paths.

use std::ffi::OsString;
use std::io;
use std::path::{Path, PathBuf};

use crate::install::{InstallOutcome, ensure_installed};

/// Environment override for the bundled-resources root: a tree that is used AS-IS and never
/// written to. It predates FLUX-001 (a packaged build's escape hatch when the build tree was the
/// only other option) and is kept for a packager or developer who wants the loader pointed at a
/// hand-maintained copy; with the bundle embedded, nothing needs it.
pub const BUNDLED_RESOURCES_DIR_ENV_VAR: &str = "CYRUP_FLUX_RESOURCES_DIR";

/// `<agent_dir>/flux/resources` — the extension-owned root the embedded bundle is materialised
/// into. Sibling of `<agent_dir>/intercom` and `<agent_dir>/subagents`; NOT `<agent_dir>/prompts`
/// or `<agent_dir>/skills`, which the user-scope loader already scans and which would register
/// every template twice (once natively, once via `promptPaths`) and expose the installer's
/// dot-file markers to a scanned directory.
#[must_use]
pub fn managed_root(agent_dir: &Path) -> PathBuf {
    agent_dir.join("flux").join("resources")
}

/// The directory `ResourcesDiscover` contributes, and how it comes to exist.
///
/// Two sources, decided at the boundary and never re-derived: a caller holding a `BundledRoot`
/// cannot contribute a path that was not produced by one of these two rules, and the
/// build-machine `CARGO_MANIFEST_DIR` is no longer a rule at all.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BundledRoot {
    /// [`BUNDLED_RESOURCES_DIR_ENV_VAR`] was set: read this tree as-is, never write into it.
    Vendored(PathBuf),
    /// The default: [`managed_root`], materialised from the embedded bundle by
    /// [`crate::install::ensure_installed`] on every `ResourcesDiscover` (cheap when up to date).
    Managed(PathBuf),
}

impl BundledRoot {
    /// Resolve against the process environment.
    #[must_use]
    pub fn resolve(agent_dir: &Path) -> Self {
        Self::resolve_from(agent_dir, &|key| std::env::var_os(key))
    }

    /// [`Self::resolve`] with the environment supplied. A set-but-blank override is unset (the
    /// `cyrup_config::paths::non_blank` rule: `PathBuf::from("")` is the relative empty path).
    #[must_use]
    pub fn resolve_from(agent_dir: &Path, env: &dyn Fn(&str) -> Option<OsString>) -> Self {
        match env(BUNDLED_RESOURCES_DIR_ENV_VAR) {
            Some(v) if !v.to_str().is_some_and(|s| s.trim().is_empty()) => {
                Self::Vendored(PathBuf::from(v))
            }
            _ => Self::Managed(managed_root(agent_dir)),
        }
    }

    /// The root directory itself.
    #[must_use]
    pub fn path(&self) -> &Path {
        match self {
            Self::Vendored(p) | Self::Managed(p) => p,
        }
    }

    /// The prompt ROOT contributed to `promptPaths` — a directory, never a file (FLUX_01 Fact 4):
    /// `add_prompt_path` loads a file by BASENAME (losing the `flux/` namespace) and a directory
    /// through the recursive namespaced scanner.
    #[must_use]
    pub fn prompts_dir(&self) -> PathBuf {
        self.path().join("prompts")
    }

    /// The bundled skill entry point contributed to `skillPaths` (FLUX_06) — a FILE:
    /// `add_skill_path` loads a `SKILL.md` path directly.
    #[must_use]
    pub fn skill_md(&self) -> PathBuf {
        self.path().join("skills").join("flux").join("SKILL.md")
    }

    /// Make the tree present. `Managed` runs the installer; `Vendored` is the operator's
    /// responsibility and is reported as up to date without touching it.
    pub fn ensure(&self) -> io::Result<InstallOutcome> {
        match self {
            Self::Vendored(_) => Ok(InstallOutcome::UpToDate),
            Self::Managed(root) => ensure_installed(root),
        }
    }
}
