//! Embeds the bundled prompt/skill tree (`resources/**`) into the crate (FLUX-001).
//!
//! `env!("CARGO_MANIFEST_DIR")` is the absolute source path of whatever machine compiled the
//! binary; a release artifact, a container image or a `cargo install` from a source dir that is
//! later cleaned has no tree there, and the fifteen `/flux/*` templates plus the skill silently
//! vanished while the three native renderers, `ctrl+f` and `ask_user_question` stayed registered.
//! Upstream never had this problem: `flux_bootstrap/installer.py` @v0.0.40 ships `bundled/` as
//! package data and copies it into `~/.code_puppy` at startup. This script is the "package data"
//! half of that port — it walks `resources/` and emits `$OUT_DIR/bundled.rs`, a sorted
//! `include_bytes!` table `src/bundle.rs` includes — so the tree travels INSIDE the binary and
//! `src/install.rs` (the copy-into-config-dir half) can materialise it anywhere.
//!
//! No hand-maintained file list: a template added under `resources/` is embedded on the next
//! build (`rerun-if-changed` covers the directory and every file in it), and
//! `tests/flux_001_embedded_bundle.rs` pins the embedded census against the on-disk tree.

#![allow(clippy::expect_used, clippy::panic)] // a build script's only failure channel is a panic

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// The `installer.py:135` skip (`p.name != ".DS_Store"`), widened to every dot-file: nothing under
/// `resources/` is meant to be hidden, and the installer's own markers (`.flux_bootstrap_*`) live
/// at the materialised root, never in the bundle.
fn is_junk(path: &Path) -> bool {
    path.file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|n| n.starts_with('.'))
}

/// Every regular file under `dir`, recursively (`installer.py:130-136` `_iter_bundled_files`).
fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cyrup-flux build.rs: reading {}: {e}", dir.display()));
    for entry in entries {
        let path = entry
            .unwrap_or_else(|e| panic!("cyrup-flux build.rs: reading {}: {e}", dir.display()))
            .path();
        if is_junk(&path) {
            continue;
        }
        if path.is_dir() {
            walk(&path, out);
        } else if path.is_file() {
            out.push(path);
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"),
    );
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let resources = manifest_dir.join("resources");
    // A directory entry re-runs on any add/remove beneath it; the per-file lines below re-run
    // on content edits.
    println!("cargo:rerun-if-changed={}", resources.display());

    let mut files = Vec::new();
    walk(&resources, &mut files);
    files.sort();

    let mut table = String::from(
        "/// Every file under `resources/`, sorted by relative path. GENERATED by `build.rs` —\n\
         /// do not edit; add files under `resources/` instead.\n\
         pub static BUNDLED_FILES: &[BundledFile] = &[\n",
    );
    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
        let rel = file
            .strip_prefix(&resources)
            .expect("walked file is under resources/")
            .to_str()
            .expect("bundled resource paths are UTF-8")
            .replace('\\', "/");
        let abs = file.to_str().expect("bundled resource paths are UTF-8");
        writeln!(
            table,
            "    BundledFile {{ rel: {rel:?}, bytes: include_bytes!({abs:?}) }},"
        )
        .expect("writing to a String cannot fail");
    }
    table.push_str("];\n");

    std::fs::write(out_dir.join("bundled.rs"), table)
        .unwrap_or_else(|e| panic!("cyrup-flux build.rs: writing bundled.rs: {e}"));
}
